// Wygenerowane przez gen_skins.py z publicznej bazy nazw skinów CS2 (ByMykel/CSGO-API).
// Broń: [id, broń, nazwa, rzadkość, cena, obrazek, kolor, typ]. Noże: [id, broń, nazwa, cena, kształt, kolor1, kolor2, wzór].
const TINTS = {"none": "", "red": "sepia(1) saturate(6) hue-rotate(-40deg) brightness(.95)", "orange": "sepia(1) saturate(5) hue-rotate(-15deg)", "gold": "sepia(1) saturate(3) hue-rotate(-5deg) brightness(1.1)", "yellow": "sepia(1) saturate(6) hue-rotate(15deg) brightness(1.15)", "green": "sepia(1) saturate(5) hue-rotate(70deg)", "teal": "sepia(1) saturate(5) hue-rotate(125deg)", "blue": "sepia(1) saturate(5) hue-rotate(175deg)", "purple": "sepia(1) saturate(5) hue-rotate(225deg)", "pink": "sepia(1) saturate(5) hue-rotate(280deg) brightness(1.05)", "white": "grayscale(1) brightness(1.55) contrast(.85)", "black": "grayscale(1) contrast(1.35) brightness(.7)", "silver": "grayscale(1) brightness(1.2) contrast(1.1)", "camo": "sepia(.9) saturate(1.3) brightness(.85)"};
const GUN_DATA = [
    ["ak-47-bloodsport", "AK-47", "Bloodsport", "covert", 58, "img/sk/ak_bloodsport.webp", "none", "gun"],
    ["ak-47-case-hardened", "AK-47", "Case Hardened", "classified", 140, "img/sk/ak_the_empress.webp", "gold", "gun"],
    ["ak-47-gold-arabesque", "AK-47", "Gold Arabesque", "covert", 900, "img/sk/ak_neon_revolution.webp", "gold", "gun"],
    ["ak-47-x-ray", "AK-47", "X-Ray", "covert", 300, "img/sk/ak_the_empress.webp", "blue", "gun"],
    ["ak-47-the-empress", "AK-47", "The Empress", "covert", 48, "img/sk/ak_the_empress.webp", "none", "gun"],
    ["ak-47-wild-lotus", "AK-47", "Wild Lotus", "covert", 1400, "img/sk/ak_the_empress.webp", "pink", "gun"],
    ["ak-47-vulcan", "AK-47", "Vulcan", "covert", 180, "img/sk/ak_vulcan.webp", "none", "gun"],
    ["ak-47-fire-serpent", "AK-47", "Fire Serpent", "covert", 950, "img/sk/ak_fire_serpent.webp", "none", "gun"],
    ["ak-47-aquamarine-revenge", "AK-47", "Aquamarine Revenge", "covert", 36, "img/sk/ak_aquamarine_revenge.webp", "none", "gun"],
    ["ak-47-neon-revolution", "AK-47", "Neon Revolution", "covert", 42, "img/sk/ak_neon_revolution.webp", "none", "gun"],
    ["ak-47-redline", "AK-47", "Redline", "classified", 25, "img/w-ak47.png", "red", "gun"],
    ["ak-47-safari-mesh", "AK-47", "Safari Mesh", "industrial", 0.35, "img/sk/ak_vulcan.webp", "camo", "gun"],
    ["ak-47-green-laminate", "AK-47", "Green Laminate", "milspec", 1.64, "img/sk/ak_aquamarine_revenge.webp", "green", "gun"],
    ["ak-47-first-class", "AK-47", "First Class", "restricted", 7.03, "img/sk/ak_fire_serpent.webp", "purple", "gun"],
    ["ak-47-nouveau-rouge", "AK-47", "Nouveau Rouge", "classified", 20.69, "img/sk/ak_neon_revolution.webp", "silver", "gun"],
    ["ak-47-consequence-of-the-jinn", "AK-47", "Consequence of the Jinn", "covert", 144.73, "img/sk/ak_bloodsport.webp", "red", "gun"],
    ["ak-47-predator", "AK-47", "Predator", "industrial", 0.53, "img/sk/ak_aquamarine_revenge.webp", "red", "gun"],
    ["ak-47-crossfade", "AK-47", "Crossfade", "milspec", 0.84, "img/sk/ak_vulcan.webp", "silver", "gun"],
    ["ak-47-slate", "AK-47", "Slate", "restricted", 11.06, "img/sk/ak_fire_serpent.webp", "black", "gun"],
    ["ak-47-ice-coaled", "AK-47", "Ice Coaled", "classified", 44.89, "img/sk/ak_aquamarine_revenge.webp", "blue", "gun"],
    ["ak-47-leet-museo", "AK-47", "Leet Museo", "covert", 46.92, "img/sk/ak_aquamarine_revenge.webp", "gold", "gun"],
    ["ak-47-jungle-spray", "AK-47", "Jungle Spray", "industrial", 0.31, "img/sk/ak_neon_revolution.webp", "green", "gun"],
    ["ak-47-steel-delta", "AK-47", "Steel Delta", "milspec", 2.06, "img/sk/ak_fire_serpent.webp", "silver", "gun"],
    ["ak-47-emerald-pinstripe", "AK-47", "Emerald Pinstripe", "restricted", 6.69, "img/sk/ak_aquamarine_revenge.webp", "green", "gun"],
    ["ak-47-crane-flight", "AK-47", "Crane Flight", "classified", 18.38, "img/sk/ak_vulcan.webp", "blue", "gun"],
    ["ak-47-the-oligarch", "AK-47", "The Oligarch", "covert", 56.84, "img/w-ak47.png", "orange", "gun"],
    ["ak-47-olive-polycam", "AK-47", "Olive Polycam", "industrial", 0.38, "img/sk/ak_neon_revolution.webp", "green", "gun"],
    ["ak-47-black-laminate", "AK-47", "Black Laminate", "milspec", 2.41, "img/sk/ak_fire_serpent.webp", "black", "gun"],
    ["ak-47-rat-rod", "AK-47", "Rat Rod", "restricted", 4.67, "img/sk/ak_neon_revolution.webp", "pink", "gun"],
    ["ak-47-jet-set", "AK-47", "Jet Set", "classified", 29.99, "img/sk/ak_the_empress.webp", "gold", "gun"],
    ["ak-47-head-shot", "AK-47", "Head Shot", "covert", 93.14, "img/sk/ak_fire_serpent.webp", "green", "gun"],
    ["ak-47-baroque-purple", "AK-47", "Baroque Purple", "industrial", 0.33, "img/sk/ak_aquamarine_revenge.webp", "purple", "gun"],
    ["ak-47-uncharted", "AK-47", "Uncharted", "milspec", 0.6, "img/sk/ak_neon_revolution.webp", "purple", "gun"],
    ["ak-47-blue-laminate", "AK-47", "Blue Laminate", "restricted", 10.11, "img/sk/ak_vulcan.webp", "blue", "gun"],
    ["ak-47-frontside-misty", "AK-47", "Frontside Misty", "classified", 33.75, "img/sk/ak_bloodsport.webp", "pink", "gun"],
    ["ak-47-neon-rider", "AK-47", "Neon Rider", "covert", 186.17, "img/sk/ak_bloodsport.webp", "gold", "gun"],
    ["awp-dragon-lore", "AWP", "Dragon Lore", "covert", 2400, "img/sk/awp_dragon_lore.webp", "none", "gun"],
    ["awp-fade", "AWP", "Fade", "covert", 900, "img/sk/awp_asiimov.webp", "silver", "gun"],
    ["awp-man-o-war", "AWP", "Man-o'-war", "covert", 18, "img/sk/awp_man_o_war.webp", "none", "gun"],
    ["awp-hyper-beast", "AWP", "Hyper Beast", "covert", 38, "img/sk/awp_hyper_beast.webp", "none", "gun"],
    ["awp-asiimov", "AWP", "Asiimov", "covert", 115, "img/sk/awp_asiimov.webp", "none", "gun"],
    ["awp-gungnir", "AWP", "Gungnir", "covert", 1100, "img/sk/awp_asiimov.webp", "blue", "gun"],
    ["awp-lightning-strike", "AWP", "Lightning Strike", "covert", 250, "img/sk/awp_asiimov.webp", "blue", "gun"],
    ["awp-the-prince", "AWP", "The Prince", "covert", 700, "img/sk/awp_asiimov.webp", "silver", "gun"],
    ["awp-medusa", "AWP", "Medusa", "covert", 900, "img/sk/awp_man_o_war.webp", "teal", "gun"],
    ["awp-sun-in-leo", "AWP", "Sun in Leo", "industrial", 0.31, "img/sk/awp_man_o_war.webp", "gold", "gun"],
    ["awp-capillary", "AWP", "Capillary", "milspec", 2.28, "img/sk/awp_hyper_beast.webp", "red", "gun"],
    ["awp-worm-god", "AWP", "Worm God", "restricted", 4.5, "img/sk/awp_dragon_lore.webp", "green", "gun"],
    ["awp-fever-dream", "AWP", "Fever Dream", "classified", 43.91, "img/sk/awp_asiimov.webp", "pink", "gun"],
    ["awp-sovereign-flame", "AWP", "Sovereign Flame", "covert", 72.59, "img/w-awp.png", "red", "gun"],
    ["awp-safari-mesh", "AWP", "Safari Mesh", "industrial", 0.37, "img/sk/awp_asiimov.webp", "camo", "gun"],
    ["awp-arsenic-spill", "AWP", "Arsenic Spill", "milspec", 2.94, "img/sk/awp_dragon_lore.webp", "blue", "gun"],
    ["awp-pink-ddpat", "AWP", "Pink DDPAT", "restricted", 10.37, "img/sk/awp_hyper_beast.webp", "pink", "gun"],
    ["awp-green-energy", "AWP", "Green Energy", "classified", 23.7, "img/sk/awp_asiimov.webp", "green", "gun"],
    ["awp-neo-noir", "AWP", "Neo-Noir", "covert", 87.49, "img/sk/awp_man_o_war.webp", "black", "gun"],
    ["awp-snake-camo", "AWP", "Snake Camo", "milspec", 1.21, "img/sk/awp_man_o_war.webp", "camo", "gun"],
    ["awp-paw", "AWP", "PAW", "restricted", 7.06, "img/sk/awp_dragon_lore.webp", "purple", "gun"],
    ["awp-graphite", "AWP", "Graphite", "classified", 10.64, "img/sk/awp_hyper_beast.webp", "black", "gun"],
    ["awp-queen-s-gambit", "AWP", "Queen's Gambit", "covert", 278.3, "img/sk/awp_asiimov.webp", "gold", "gun"],
    ["awp-black-nile", "AWP", "Black Nile", "milspec", 0.69, "img/sk/awp_asiimov.webp", "black", "gun"],
    ["awp-exothermic", "AWP", "Exothermic", "restricted", 9.79, "img/sk/awp_asiimov.webp", "gold", "gun"],
    ["awp-boom", "AWP", "BOOM", "classified", 22.63, "img/sk/awp_asiimov.webp", "teal", "gun"],
    ["awp-wildfire", "AWP", "Wildfire", "covert", 113.84, "img/w-awp.png", "red", "gun"],
    ["awp-acheron", "AWP", "Acheron", "milspec", 2.37, "img/sk/awp_asiimov.webp", "teal", "gun"],
    ["awp-atheris", "AWP", "Atheris", "restricted", 6.12, "img/w-awp.png", "gold", "gun"],
    ["awp-mortis", "AWP", "Mortis", "classified", 16.17, "img/sk/awp_hyper_beast.webp", "silver", "gun"],
    ["awp-desert-hydra", "AWP", "Desert Hydra", "covert", 129.32, "img/sk/awp_asiimov.webp", "green", "gun"],
    ["awp-black-box", "AWP", "Black Box", "restricted", 3.3, "img/sk/awp_hyper_beast.webp", "black", "gun"],
    ["awp-elite-build", "AWP", "Elite Build", "classified", 13.74, "img/sk/awp_man_o_war.webp", "gold", "gun"],
    ["awp-chrome-cannon", "AWP", "Chrome Cannon", "covert", 118.66, "img/w-awp.png", "silver", "gun"],
    ["awp-pop-awp", "AWP", "POP AWP", "restricted", 8.5, "img/sk/awp_asiimov.webp", "teal", "gun"],
    ["awp-the-end", "AWP", "The End", "classified", 14.33, "img/sk/awp_man_o_war.webp", "silver", "gun"],
    ["m4a1-s-mecha-industries", "M4A1-S", "Mecha Industries", "covert", 14, "img/sk/m4a1s_mecha_industries.webp", "none", "gun"],
    ["m4a1-s-chantico-s-fire", "M4A1-S", "Chantico's Fire", "covert", 38, "img/sk/m4a1s_chanticos_fire.webp", "none", "gun"],
    ["m4a1-s-welcome-to-the-jungle", "M4A1-S", "Welcome to the Jungle", "covert", 450, "img/w-m4a1s.png", "green", "gun"],
    ["m4a1-s-cyrex", "M4A1-S", "Cyrex", "covert", 45.59, "img/w-m4a1s.png", "red", "gun"],
    ["m4a1-s-printstream", "M4A1-S", "Printstream", "covert", 90, "img/sk/m4a1s_hyper_beast.webp", "white", "gun"],
    ["m4a1-s-hyper-beast", "M4A1-S", "Hyper Beast", "covert", 24, "img/sk/m4a1s_hyper_beast.webp", "none", "gun"],
    ["m4a1-s-knight", "M4A1-S", "Knight", "classified", 600, "img/sk/m4a1s_chanticos_fire.webp", "black", "gun"],
    ["m4a1-s-golden-coil", "M4A1-S", "Golden Coil", "covert", 32, "img/sk/m4a1s_golden_coil.webp", "none", "gun"],
    ["m4a1-s-hot-rod", "M4A1-S", "Hot Rod", "classified", 300, "img/sk/m4a1s_chanticos_fire.webp", "red", "gun"],
    ["m4a1-s-moss-quartz", "M4A1-S", "Moss Quartz", "industrial", 0.47, "img/sk/m4a1s_golden_coil.webp", "green", "gun"],
    ["m4a1-s-blood-tiger", "M4A1-S", "Blood Tiger", "milspec", 1.67, "img/sk/m4a1s_chanticos_fire.webp", "red", "gun"],
    ["m4a1-s-night-terror", "M4A1-S", "Night Terror", "restricted", 11.54, "img/sk/m4a1s_chanticos_fire.webp", "black", "gun"],
    ["m4a1-s-black-lotus", "M4A1-S", "Black Lotus", "classified", 55.11, "img/w-m4a1s.png", "pink", "gun"],
    ["m4a1-s-vaporwave", "M4A1-S", "Vaporwave", "covert", 73.94, "img/sk/m4a1s_golden_coil.webp", "teal", "gun"],
    ["m4a1-s-mud-spec", "M4A1-S", "Mud-Spec", "industrial", 0.28, "img/sk/m4a1s_golden_coil.webp", "purple", "gun"],
    ["m4a1-s-rose-hex", "M4A1-S", "Rose Hex", "milspec", 1.11, "img/sk/m4a1s_hyper_beast.webp", "pink", "gun"],
    ["m4a1-s-bright-water", "M4A1-S", "Bright Water", "restricted", 3.94, "img/sk/m4a1s_golden_coil.webp", "blue", "gun"],
    ["m4a1-s-solitude", "M4A1-S", "Solitude", "classified", 31.99, "img/sk/m4a1s_hyper_beast.webp", "teal", "gun"],
    ["m4a1-s-imminent-danger", "M4A1-S", "Imminent Danger", "covert", 237.73, "img/sk/m4a1s_golden_coil.webp", "purple", "gun"],
    ["m4a1-s-boreal-forest", "M4A1-S", "Boreal Forest", "industrial", 0.2, "img/w-m4a1s.png", "green", "gun"],
    ["m4a1-s-varicamo", "M4A1-S", "VariCamo", "milspec", 2.98, "img/sk/m4a1s_chanticos_fire.webp", "camo", "gun"],
    ["m4a1-s-liquidation", "M4A1-S", "Liquidation", "restricted", 11.35, "img/w-m4a1s.png", "purple", "gun"],
    ["m4a1-s-party-animal", "M4A1-S", "Party Animal", "classified", 30.31, "img/sk/m4a1s_chanticos_fire.webp", "blue", "gun"],
    ["m4a1-s-player-two", "M4A1-S", "Player Two", "covert", 85.78, "img/sk/m4a1s_chanticos_fire.webp", "green", "gun"],
    ["m4a1-s-wash-me-plz", "M4A1-S", "Wash me plz", "industrial", 0.54, "img/sk/m4a1s_golden_coil.webp", "pink", "gun"],
    ["m4a1-s-briefing", "M4A1-S", "Briefing", "milspec", 1.63, "img/w-m4a1s.png", "gold", "gun"],
    ["m4a1-s-flashback", "M4A1-S", "Flashback", "restricted", 3.48, "img/w-m4a1s.png", "blue", "gun"],
    ["m4a1-s-decimator", "M4A1-S", "Decimator", "classified", 20.2, "img/sk/m4a1s_mecha_industries.webp", "pink", "gun"],
    ["m4a1-s-fade", "M4A1-S", "Fade", "covert", 30.36, "img/sk/m4a1s_golden_coil.webp", "silver", "gun"],
    ["m4a1-s-fizzy-pop", "M4A1-S", "Fizzy POP", "milspec", 0.73, "img/sk/m4a1s_mecha_industries.webp", "purple", "gun"],
    ["m4a1-s-emphorosaur-s", "M4A1-S", "Emphorosaur-S", "restricted", 3.66, "img/w-m4a1s.png", "blue", "gun"],
    ["m4a1-s-nightmare", "M4A1-S", "Nightmare", "classified", 34.73, "img/w-m4a1s.png", "black", "gun"],
    ["m4a1-s-electrum", "M4A1-S", "Electrum", "restricted", 3.96, "img/sk/m4a1s_mecha_industries.webp", "purple", "gun"],
    ["m4a1-s-leaded-glass", "M4A1-S", "Leaded Glass", "classified", 30.6, "img/w-m4a1s.png", "blue", "gun"],
    ["m4a1-s-dark-water", "M4A1-S", "Dark Water", "restricted", 6.93, "img/sk/m4a1s_mecha_industries.webp", "teal", "gun"],
    ["m4a1-s-stratosphere", "M4A1-S", "Stratosphere", "classified", 7.34, "img/sk/m4a1s_golden_coil.webp", "blue", "gun"],
    ["m4a4-desert-strike", "M4A4", "Desert-Strike", "covert", 9, "img/sk/m4a4_desert_strike.webp", "none", "gun"],
    ["m4a4-howl", "M4A4", "Howl", "covert", 1300, "img/w-m4a4.png", "red", "gun"],
    ["m4a4-buzz-kill", "M4A4", "Buzz Kill", "covert", 55, "img/sk/m4a4_buzz_kill.webp", "none", "gun"],
    ["m4a4-urban-ddpat", "M4A4", "Urban DDPAT", "industrial", 0.29, "img/w-m4a4.png", "silver", "gun"],
    ["m4a4-zubastick", "M4A4", "Zubastick", "milspec", 1.26, "img/w-m4a4.png", "teal", "gun"],
    ["m4a4-zirka", "M4A4", "Zirka", "restricted", 4.14, "img/sk/m4a4_buzz_kill.webp", "blue", "gun"],
    ["m4a4-hellish", "M4A4", "Hellish", "classified", 14.0, "img/sk/m4a4_desert_strike.webp", "silver", "gun"],
    ["m4a4-in-living-color", "M4A4", "In Living Color", "covert", 79.29, "img/sk/m4a4_buzz_kill.webp", "orange", "gun"],
    ["m4a4-mainframe", "M4A4", "Mainframe", "industrial", 0.24, "img/sk/m4a4_desert_strike.webp", "green", "gun"],
    ["m4a4-dark-operative", "M4A4", "Dark Operative", "milspec", 1.13, "img/w-m4a4.png", "black", "gun"],
    ["m4a4-daybreak", "M4A4", "Daybreak", "restricted", 6.5, "img/w-m4a4.png", "yellow", "gun"],
    ["m4a4-cyber-security", "M4A4", "Cyber Security", "classified", 28.49, "img/sk/m4a4_buzz_kill.webp", "blue", "gun"],
    ["m4a4-temukau", "M4A4", "Temukau", "covert", 131.39, "img/sk/m4a4_buzz_kill.webp", "orange", "gun"],
    ["m4a4-jungle-tiger", "M4A4", "Jungle Tiger", "industrial", 0.35, "img/sk/m4a4_buzz_kill.webp", "green", "gun"],
    ["m4a4-radiation-hazard", "M4A4", "Radiation Hazard", "milspec", 0.68, "img/sk/m4a4_buzz_kill.webp", "orange", "gun"],
    ["m4a4-modern-hunter", "M4A4", "Modern Hunter", "restricted", 6.07, "img/w-m4a4.png", "camo", "gun"],
    ["m4a4-dragon-king", "M4A4", "龍王 (Dragon King)", "classified", 22.25, "img/sk/m4a4_buzz_kill.webp", "red", "gun"],
    ["m4a4-the-coalition", "M4A4", "The Coalition", "covert", 116.81, "img/sk/m4a4_buzz_kill.webp", "blue", "gun"],
    ["m4a4-steel-work", "M4A4", "Steel Work", "industrial", 0.13, "img/w-m4a4.png", "silver", "gun"],
    ["m4a4-faded-zebra", "M4A4", "Faded Zebra", "milspec", 0.96, "img/sk/m4a4_buzz_kill.webp", "silver", "gun"],
    ["m4a4-turbine", "M4A4", "Turbine", "restricted", 4.8, "img/sk/m4a4_buzz_kill.webp", "pink", "gun"],
    ["m4a4-tooth-fairy", "M4A4", "Tooth Fairy", "classified", 39.11, "img/sk/m4a4_buzz_kill.webp", "pink", "gun"],
    ["m4a4-neo-noir", "M4A4", "Neo-Noir", "covert", 24.05, "img/sk/m4a4_buzz_kill.webp", "black", "gun"],
    ["m4a4-tornado", "M4A4", "Tornado", "industrial", 0.24, "img/sk/m4a4_desert_strike.webp", "gold", "gun"],
    ["m4a4-converter", "M4A4", "Converter", "milspec", 0.76, "img/sk/m4a4_buzz_kill.webp", "orange", "gun"],
    ["m4a4-polysoup", "M4A4", "Polysoup", "restricted", 3.77, "img/sk/m4a4_buzz_kill.webp", "pink", "gun"],
    ["m4a4-hellfire", "M4A4", "Hellfire", "classified", 17.54, "img/sk/m4a4_desert_strike.webp", "red", "gun"],
    ["m4a4-bullet-rain", "M4A4", "Bullet Rain", "covert", 189.79, "img/sk/m4a4_buzz_kill.webp", "orange", "gun"],
    ["m4a4-desert-storm", "M4A4", "Desert Storm", "industrial", 0.12, "img/sk/m4a4_buzz_kill.webp", "blue", "gun"],
    ["m4a4-magnesium", "M4A4", "Magnesium", "milspec", 0.38, "img/w-m4a4.png", "purple", "gun"],
    ["m4a4-sheet-lightning", "M4A4", "Sheet Lightning", "restricted", 4.19, "img/sk/m4a4_desert_strike.webp", "blue", "gun"],
    ["m4a4-desolate-space", "M4A4", "Desolate Space", "classified", 13.7, "img/w-m4a4.png", "teal", "gun"],
    ["m4a4-the-battlestar", "M4A4", "The Battlestar", "covert", 113.26, "img/w-m4a4.png", "red", "gun"],
    ["m4a4-aeolian-dark", "M4A4", "Aeolian Dark", "industrial", 0.23, "img/sk/m4a4_buzz_kill.webp", "black", "gun"],
    ["m4a4-choppa", "M4A4", "Choppa", "milspec", 0.61, "img/sk/m4a4_desert_strike.webp", "green", "gun"],
    ["m4a4-red-ddpat", "M4A4", "Red DDPAT", "restricted", 6.99, "img/sk/m4a4_desert_strike.webp", "red", "gun"],
    ["galil-ar-chatterbox", "Galil AR", "Chatterbox", "covert", 7, "img/sk/galil_chatterbox.webp", "none", "gun"],
    ["galil-ar-grey-smoke", "Galil AR", "Grey Smoke", "consumer", 0.06, "img/w-galil.png", "silver", "gun"],
    ["galil-ar-nv", "Galil AR", "NV", "industrial", 0.12, "img/w-galil.png", "red", "gun"],
    ["galil-ar-shattered", "Galil AR", "Shattered", "milspec", 0.77, "img/w-galil.png", "red", "gun"],
    ["galil-ar-connexion", "Galil AR", "Connexion", "restricted", 3.12, "img/w-galil.png", "green", "gun"],
    ["galil-ar-chromatic-aberration", "Galil AR", "Chromatic Aberration", "classified", 10.18, "img/w-galil.png", "green", "gun"],
    ["galil-ar-hunting-blind", "Galil AR", "Hunting Blind", "consumer", 0.06, "img/w-galil.png", "red", "gun"],
    ["galil-ar-o-ranger", "Galil AR", "O-Ranger", "industrial", 0.51, "img/w-galil.png", "blue", "gun"],
    ["galil-ar-blue-titanium", "Galil AR", "Blue Titanium", "milspec", 0.69, "img/w-galil.png", "blue", "gun"],
    ["galil-ar-stone-cold", "Galil AR", "Stone Cold", "restricted", 3.98, "img/w-galil.png", "silver", "gun"],
    ["galil-ar-eco", "Galil AR", "Eco", "classified", 13.81, "img/w-galil.png", "silver", "gun"],
    ["galil-ar-tornado", "Galil AR", "Tornado", "consumer", 0.03, "img/w-galil.png", "teal", "gun"],
    ["galil-ar-acid-dart", "Galil AR", "Acid Dart", "industrial", 0.45, "img/w-galil.png", "green", "gun"],
    ["galil-ar-amber-fade", "Galil AR", "Amber Fade", "milspec", 0.34, "img/w-galil.png", "orange", "gun"],
    ["galil-ar-caution", "Galil AR", "CAUTION!", "restricted", 4.29, "img/w-galil.png", "pink", "gun"],
    ["galil-ar-rainbow-spoon", "Galil AR", "Rainbow Spoon", "classified", 53.49, "img/w-galil.png", "blue", "gun"],
    ["galil-ar-sage-spray", "Galil AR", "Sage Spray", "consumer", 0.04, "img/w-galil.png", "camo", "gun"],
    ["galil-ar-winter-forest", "Galil AR", "Winter Forest", "industrial", 0.29, "img/w-galil.png", "green", "gun"],
    ["galil-ar-vandal", "Galil AR", "Vandal", "milspec", 0.41, "img/w-galil.png", "purple", "gun"],
    ["galil-ar-crimson-tsunami", "Galil AR", "Crimson Tsunami", "restricted", 1.5, "img/w-galil.png", "red", "gun"],
    ["galil-ar-sugar-rush", "Galil AR", "Sugar Rush", "classified", 9.82, "img/w-galil.png", "pink", "gun"],
    ["galil-ar-cold-fusion", "Galil AR", "Cold Fusion", "industrial", 0.44, "img/w-galil.png", "red", "gun"],
    ["galil-ar-aqua-terrace", "Galil AR", "Aqua Terrace", "milspec", 0.46, "img/w-galil.png", "teal", "gun"],
    ["galil-ar-phoenix-blacklight", "Galil AR", "Phoenix Blacklight", "restricted", 5.18, "img/w-galil.png", "black", "gun"],
    ["galil-ar-green-apple", "Galil AR", "Green Apple", "industrial", 0.11, "img/w-galil.png", "green", "gun"],
    ["galil-ar-black-sand", "Galil AR", "Black Sand", "milspec", 0.35, "img/w-galil.png", "black", "gun"],
    ["galil-ar-cerberus", "Galil AR", "Cerberus", "restricted", 2.67, "img/w-galil.png", "red", "gun"],
    ["galil-ar-robin-s-egg", "Galil AR", "Robin's Egg", "industrial", 0.16, "img/w-galil.png", "purple", "gun"],
    ["galil-ar-sandstorm", "Galil AR", "Sandstorm", "milspec", 0.75, "img/w-galil.png", "blue", "gun"],
    ["galil-ar-signal", "Galil AR", "Signal", "restricted", 3.37, "img/w-galil.png", "red", "gun"],
    ["galil-ar-varicamo", "Galil AR", "VariCamo", "industrial", 0.09, "img/w-galil.png", "camo", "gun"],
    ["galil-ar-rocket-pop", "Galil AR", "Rocket Pop", "milspec", 0.39, "img/w-galil.png", "pink", "gun"],
    ["galil-ar-firefight", "Galil AR", "Firefight", "restricted", 2.67, "img/w-galil.png", "red", "gun"],
    ["galil-ar-urban-rubble", "Galil AR", "Urban Rubble", "industrial", 0.2, "img/w-galil.png", "silver", "gun"],
    ["galil-ar-sky-mandala", "Galil AR", "Sky Mandala", "milspec", 0.48, "img/w-galil.png", "blue", "gun"],
    ["galil-ar-galigator", "Galil AR", "Galigator", "restricted", 2.18, "img/w-galil.png", "gold", "gun"],
    ["usp-s-kill-confirmed", "USP-S", "Kill Confirmed", "covert", 60, "img/sk/usps_kill_confirmed.webp", "none", "gun"],
    ["usp-s-para-green", "USP-S", "Para Green", "industrial", 0.08, "img/sk/usps_kill_confirmed.webp", "green", "gun"],
    ["usp-s-alpine-camo", "USP-S", "Alpine Camo", "milspec", 0.34, "img/sk/usps_kill_confirmed.webp", "camo", "gun"],
    ["usp-s-sleeping-potion", "USP-S", "Sleeping Potion", "restricted", 8.44, "img/w-usps.png", "silver", "gun"],
    ["usp-s-target-acquired", "USP-S", "Target Acquired", "classified", 15.77, "img/w-usps.png", "red", "gun"],
    ["usp-s-neo-noir", "USP-S", "Neo-Noir", "covert", 51.42, "img/w-usps.png", "black", "gun"],
    ["usp-s-royal-blue", "USP-S", "Royal Blue", "industrial", 0.41, "img/sk/usps_kill_confirmed.webp", "blue", "gun"],
    ["usp-s-black-lotus", "USP-S", "Black Lotus", "milspec", 0.4, "img/sk/usps_kill_confirmed.webp", "pink", "gun"],
    ["usp-s-dark-water", "USP-S", "Dark Water", "restricted", 6.86, "img/sk/usps_kill_confirmed.webp", "teal", "gun"],
    ["usp-s-caiman", "USP-S", "Caiman", "classified", 10.26, "img/sk/usps_kill_confirmed.webp", "blue", "gun"],
    ["usp-s-the-traitor", "USP-S", "The Traitor", "covert", 58.91, "img/sk/usps_kill_confirmed.webp", "purple", "gun"],
    ["usp-s-pathfinder", "USP-S", "Pathfinder", "industrial", 0.25, "img/w-usps.png", "orange", "gun"],
    ["usp-s-purple-ddpat", "USP-S", "Purple DDPAT", "milspec", 1.35, "img/w-usps.png", "purple", "gun"],
    ["usp-s-ticket-to-hell", "USP-S", "Ticket to Hell", "restricted", 3.95, "img/w-usps.png", "purple", "gun"],
    ["usp-s-cortex", "USP-S", "Cortex", "classified", 17.11, "img/w-usps.png", "pink", "gun"],
    ["usp-s-printstream", "USP-S", "Printstream", "covert", 45.85, "img/w-usps.png", "white", "gun"],
    ["usp-s-desert-tactical", "USP-S", "Desert Tactical", "industrial", 0.11, "img/sk/usps_kill_confirmed.webp", "camo", "gun"],
    ["usp-s-torque", "USP-S", "Torque", "milspec", 0.64, "img/w-usps.png", "purple", "gun"],
    ["usp-s-road-rash", "USP-S", "Road Rash", "restricted", 3.79, "img/sk/usps_kill_confirmed.webp", "pink", "gun"],
    ["usp-s-whiteout", "USP-S", "Whiteout", "classified", 8.15, "img/w-usps.png", "white", "gun"],
    ["usp-s-forest-leaves", "USP-S", "Forest Leaves", "industrial", 0.16, "img/sk/usps_kill_confirmed.webp", "green", "gun"],
    ["usp-s-stainless", "USP-S", "Stainless", "milspec", 1.34, "img/sk/usps_kill_confirmed.webp", "gold", "gun"],
    ["usp-s-ancient-visions", "USP-S", "Ancient Visions", "restricted", 5.43, "img/w-usps.png", "silver", "gun"],
    ["usp-s-orion", "USP-S", "Orion", "classified", 15.18, "img/w-usps.png", "red", "gun"],
    ["usp-s-night-ops", "USP-S", "Night Ops", "milspec", 0.62, "img/w-usps.png", "black", "gun"],
    ["usp-s-flashback", "USP-S", "Flashback", "restricted", 8.62, "img/w-usps.png", "red", "gun"],
    ["usp-s-jawbreaker", "USP-S", "Jawbreaker", "classified", 22.09, "img/w-usps.png", "teal", "gun"],
    ["usp-s-pc-grn", "USP-S", "PC-GRN", "milspec", 0.62, "img/w-usps.png", "silver", "gun"],
    ["usp-s-royal-guard", "USP-S", "Royal Guard", "restricted", 4.07, "img/w-usps.png", "blue", "gun"],
    ["usp-s-serum", "USP-S", "Serum", "classified", 17.99, "img/w-usps.png", "purple", "gun"],
    ["usp-s-silent-shot", "USP-S", "Silent Shot", "milspec", 0.99, "img/w-usps.png", "green", "gun"],
    ["usp-s-guardian", "USP-S", "Guardian", "restricted", 1.73, "img/w-usps.png", "green", "gun"],
    ["usp-s-spiral-glitch", "USP-S", "Spiral Glitch", "classified", 8.55, "img/w-usps.png", "silver", "gun"],
    ["usp-s-27", "USP-S", "27", "milspec", 1.11, "img/sk/usps_kill_confirmed.webp", "blue", "gun"],
    ["usp-s-cyrex", "USP-S", "Cyrex", "restricted", 4.25, "img/sk/usps_kill_confirmed.webp", "purple", "gun"],
    ["usp-s-monster-mashup", "USP-S", "Monster Mashup", "classified", 11.79, "img/w-usps.png", "gold", "gun"],
    ["ssg-08-dragonfire", "SSG 08", "Dragonfire", "covert", 45, "img/sk/ssg_dragonfire.webp", "none", "gun"],
    ["ssg-08-sand-dune", "SSG 08", "Sand Dune", "consumer", 0.04, "img/sk/ssg_dragonfire.webp", "camo", "gun"],
    ["ssg-08-tropical-storm", "SSG 08", "Tropical Storm", "industrial", 0.1, "img/w-ssg08.png", "blue", "gun"],
    ["ssg-08-dark-water", "SSG 08", "Dark Water", "milspec", 1.91, "img/sk/ssg_dragonfire.webp", "teal", "gun"],
    ["ssg-08-sea-calico", "SSG 08", "Sea Calico", "restricted", 3.31, "img/sk/ssg_dragonfire.webp", "teal", "gun"],
    ["ssg-08-big-iron", "SSG 08", "Big Iron", "classified", 7.0, "img/sk/ssg_dragonfire.webp", "silver", "gun"],
    ["ssg-08-blood-in-the-water", "SSG 08", "Blood in the Water", "covert", 68.14, "img/w-ssg08.png", "red", "gun"],
    ["ssg-08-jungle-dashed", "SSG 08", "Jungle Dashed", "consumer", 0.04, "img/sk/ssg_dragonfire.webp", "green", "gun"],
    ["ssg-08-calligrafaux", "SSG 08", "Calligrafaux", "industrial", 0.24, "img/w-ssg08.png", "green", "gun"],
    ["ssg-08-memorial", "SSG 08", "Memorial", "milspec", 0.51, "img/sk/ssg_dragonfire.webp", "green", "gun"],
    ["ssg-08-ghost-crusader", "SSG 08", "Ghost Crusader", "restricted", 1.89, "img/sk/ssg_dragonfire.webp", "white", "gun"],
    ["ssg-08-death-strike", "SSG 08", "Death Strike", "classified", 8.91, "img/w-ssg08.png", "red", "gun"],
    ["ssg-08-red-stone", "SSG 08", "Red Stone", "consumer", 0.08, "img/sk/ssg_dragonfire.webp", "red", "gun"],
    ["ssg-08-tiger-tear", "SSG 08", "Tiger Tear", "industrial", 0.32, "img/sk/ssg_dragonfire.webp", "orange", "gun"],
    ["ssg-08-threat-detected", "SSG 08", "Threat Detected", "milspec", 0.27, "img/w-ssg08.png", "red", "gun"],
    ["ssg-08-death-s-head", "SSG 08", "Death's Head", "restricted", 3.79, "img/w-ssg08.png", "green", "gun"],
    ["ssg-08-turbo-peek", "SSG 08", "Turbo Peek", "classified", 10.61, "img/sk/ssg_dragonfire.webp", "pink", "gun"],
    ["ssg-08-lichen-dashed", "SSG 08", "Lichen Dashed", "consumer", 0.11, "img/sk/ssg_dragonfire.webp", "teal", "gun"],
    ["ssg-08-halftone-whorl", "SSG 08", "Halftone Whorl", "industrial", 0.14, "img/w-ssg08.png", "red", "gun"],
    ["ssg-08-dezastre", "SSG 08", "Dezastre", "milspec", 1.07, "img/w-ssg08.png", "green", "gun"],
    ["ssg-08-parallax", "SSG 08", "Parallax", "restricted", 1.3, "img/sk/ssg_dragonfire.webp", "teal", "gun"],
    ["ssg-08-bloodshot", "SSG 08", "Bloodshot", "classified", 10.11, "img/w-ssg08.png", "red", "gun"],
    ["ssg-08-green-ceramic", "SSG 08", "Green Ceramic", "consumer", 0.06, "img/w-ssg08.png", "green", "gun"],
    ["ssg-08-mayan-dreams", "SSG 08", "Mayan Dreams", "industrial", 0.11, "img/sk/ssg_dragonfire.webp", "orange", "gun"],
    ["ssg-08-blush-pour", "SSG 08", "Blush Pour", "milspec", 2.26, "img/w-ssg08.png", "pink", "gun"],
    ["ssg-08-rapid-transit", "SSG 08", "Rapid Transit", "restricted", 3.96, "img/sk/ssg_dragonfire.webp", "pink", "gun"],
    ["ssg-08-blue-spruce", "SSG 08", "Blue Spruce", "consumer", 0.03, "img/w-ssg08.png", "blue", "gun"],
    ["ssg-08-azure-glyph", "SSG 08", "Azure Glyph", "industrial", 0.27, "img/sk/ssg_dragonfire.webp", "blue", "gun"],
    ["ssg-08-detour", "SSG 08", "Detour", "milspec", 0.61, "img/sk/ssg_dragonfire.webp", "orange", "gun"],
    ["ssg-08-fever-dream", "SSG 08", "Fever Dream", "restricted", 1.96, "img/w-ssg08.png", "pink", "gun"],
    ["ssg-08-prey", "SSG 08", "Prey", "consumer", 0.06, "img/sk/ssg_dragonfire.webp", "orange", "gun"],
    ["ssg-08-carbon-fiber", "SSG 08", "Carbon Fiber", "industrial", 0.11, "img/sk/ssg_dragonfire.webp", "black", "gun"],
    ["ssg-08-necropos", "SSG 08", "Necropos", "milspec", 0.6, "img/w-ssg08.png", "red", "gun"],
    ["ssg-08-grey-smoke", "SSG 08", "Grey Smoke", "consumer", 0.06, "img/sk/ssg_dragonfire.webp", "silver", "gun"],
    ["ssg-08-acid-fade", "SSG 08", "Acid Fade", "milspec", 0.77, "img/sk/ssg_dragonfire.webp", "green", "gun"],
    ["ssg-08-sans-comic", "SSG 08", "Sans Comic", "consumer", 0.05, "img/w-ssg08.png", "purple", "gun"],
    ["glock-18-fade", "Glock-18", "Fade", "restricted", 700, "img/w-glock.png", "silver", "gun"],
    ["glock-18-ocean-topo", "Glock-18", "Ocean Topo", "industrial", 0.13, "img/w-glock.png", "teal", "gun"],
    ["glock-18-oxide-blaze", "Glock-18", "Oxide Blaze", "milspec", 1.51, "img/w-glock.png", "red", "gun"],
    ["glock-18-glockingbird", "Glock-18", "Glockingbird", "restricted", 3.17, "img/w-glock.png", "gold", "gun"],
    ["glock-18-axia", "Glock-18", "AXIA", "classified", 24.33, "img/w-glock.png", "blue", "gun"],
    ["glock-18-gold-toof", "Glock-18", "Gold Toof", "covert", 94.73, "img/w-glock.png", "gold", "gun"],
    ["glock-18-sand-dune", "Glock-18", "Sand Dune", "industrial", 0.18, "img/w-glock.png", "camo", "gun"],
    ["glock-18-warhawk", "Glock-18", "Warhawk", "milspec", 0.66, "img/w-glock.png", "teal", "gun"],
    ["glock-18-block-18", "Glock-18", "Block-18", "restricted", 2.54, "img/w-glock.png", "teal", "gun"],
    ["glock-18-snack-attack", "Glock-18", "Snack Attack", "classified", 26.65, "img/w-glock.png", "blue", "gun"],
    ["glock-18-fully-tuned", "Glock-18", "Fully Tuned", "covert", 164.95, "img/w-glock.png", "pink", "gun"],
    ["glock-18-night", "Glock-18", "Night", "industrial", 0.53, "img/w-glock.png", "black", "gun"],
    ["glock-18-sacrifice", "Glock-18", "Sacrifice", "milspec", 0.81, "img/w-glock.png", "blue", "gun"],
    ["glock-18-trace-lock", "Glock-18", "Trace Lock", "restricted", 5.52, "img/w-glock.png", "pink", "gun"],
    ["glock-18-mirror-mosaic", "Glock-18", "Mirror Mosaic", "classified", 24.48, "img/w-glock.png", "teal", "gun"],
    ["glock-18-wasteland-rebel", "Glock-18", "Wasteland Rebel", "covert", 86.98, "img/w-glock.png", "orange", "gun"],
    ["glock-18-groundwater", "Glock-18", "Groundwater", "industrial", 0.12, "img/w-glock.png", "teal", "gun"],
    ["glock-18-off-world", "Glock-18", "Off World", "milspec", 0.75, "img/w-glock.png", "purple", "gun"],
    ["glock-18-pink-ddpat", "Glock-18", "Pink DDPAT", "restricted", 3.84, "img/w-glock.png", "pink", "gun"],
    ["glock-18-shinobu", "Glock-18", "Shinobu", "classified", 16.89, "img/w-glock.png", "red", "gun"],
    ["glock-18-neo-noir", "Glock-18", "Neo-Noir", "covert", 204.27, "img/w-glock.png", "black", "gun"],
    ["glock-18-death-rattle", "Glock-18", "Death Rattle", "industrial", 0.37, "img/w-glock.png", "purple", "gun"],
    ["glock-18-coral-bloom", "Glock-18", "Coral Bloom", "milspec", 0.9, "img/w-glock.png", "pink", "gun"],
    ["glock-18-brass", "Glock-18", "Brass", "restricted", 2.77, "img/w-glock.png", "gold", "gun"],
    ["glock-18-water-elemental", "Glock-18", "Water Elemental", "classified", 13.09, "img/w-glock.png", "teal", "gun"],
    ["glock-18-gamma-doppler", "Glock-18", "Gamma Doppler", "covert", 72.06, "img/w-glock.png", "purple", "gun"],
    ["glock-18-high-beam", "Glock-18", "High Beam", "industrial", 0.41, "img/w-glock.png", "gold", "gun"],
    ["glock-18-candy-apple", "Glock-18", "Candy Apple", "milspec", 0.83, "img/w-glock.png", "pink", "gun"],
    ["glock-18-dragon-tattoo", "Glock-18", "Dragon Tattoo", "restricted", 2.72, "img/w-glock.png", "red", "gun"],
    ["glock-18-twilight-galaxy", "Glock-18", "Twilight Galaxy", "classified", 19.34, "img/w-glock.png", "pink", "gun"],
    ["glock-18-bullet-queen", "Glock-18", "Bullet Queen", "covert", 34.55, "img/w-glock.png", "teal", "gun"],
    ["glock-18-red-tire", "Glock-18", "Red Tire", "industrial", 0.15, "img/w-glock.png", "red", "gun"],
    ["glock-18-blue-fissure", "Glock-18", "Blue Fissure", "milspec", 0.8, "img/w-glock.png", "blue", "gun"],
    ["glock-18-grinder", "Glock-18", "Grinder", "restricted", 3.75, "img/w-glock.png", "orange", "gun"],
    ["glock-18-vogue", "Glock-18", "Vogue", "classified", 29.65, "img/w-glock.png", "green", "gun"],
    ["glock-18-ghost-protocol", "Glock-18", "Ghost Protocol", "covert", 39.89, "img/w-glock.png", "white", "gun"],
    ["p90-asiimov", "P90", "Asiimov", "covert", 22, "img/sk/p90_asiimov.webp", "none", "gun"],
    ["p90-desert-halftone", "P90", "Desert Halftone", "consumer", 0.05, "img/sk/p90_asiimov.webp", "camo", "gun"],
    ["p90-wash-me", "P90", "Wash me", "industrial", 0.07, "img/sk/p90_asiimov.webp", "purple", "gun"],
    ["p90-glacier-mesh", "P90", "Glacier Mesh", "milspec", 0.25, "img/sk/p90_asiimov.webp", "teal", "gun"],
    ["p90-astral-jormungandr", "P90", "Astral Jörmungandr", "restricted", 2.31, "img/sk/p90_asiimov.webp", "pink", "gun"],
    ["p90-nostalgia", "P90", "Nostalgia", "classified", 14.57, "img/sk/p90_asiimov.webp", "silver", "gun"],
    ["p90-death-by-kitty", "P90", "Death by Kitty", "covert", 24.38, "img/sk/p90_asiimov.webp", "green", "gun"],
    ["p90-desert-ddpat", "P90", "Desert DDPAT", "consumer", 0.07, "img/sk/p90_asiimov.webp", "camo", "gun"],
    ["p90-leather", "P90", "Leather", "industrial", 0.39, "img/sk/p90_asiimov.webp", "green", "gun"],
    ["p90-baroque-red", "P90", "Baroque Red", "milspec", 0.36, "img/sk/p90_asiimov.webp", "red", "gun"],
    ["p90-attack-vector", "P90", "Attack Vector", "restricted", 4.14, "img/sk/p90_asiimov.webp", "green", "gun"],
    ["p90-shallow-grave", "P90", "Shallow Grave", "classified", 18.24, "img/sk/p90_asiimov.webp", "gold", "gun"],
    ["p90-sand-spray", "P90", "Sand Spray", "consumer", 0.06, "img/sk/p90_asiimov.webp", "camo", "gun"],
    ["p90-sunset-lily", "P90", "Sunset Lily", "industrial", 0.22, "img/sk/p90_asiimov.webp", "gold", "gun"],
    ["p90-traction", "P90", "Traction", "milspec", 0.5, "img/sk/p90_asiimov.webp", "red", "gun"],
    ["p90-wave-breaker", "P90", "Wave Breaker", "restricted", 1.78, "img/sk/p90_asiimov.webp", "orange", "gun"],
    ["p90-deathgaze", "P90", "Deathgaze", "classified", 9.42, "img/sk/p90_asiimov.webp", "silver", "gun"],
    ["p90-storm", "P90", "Storm", "consumer", 0.03, "img/sk/p90_asiimov.webp", "blue", "gun"],
    ["p90-ash-wood", "P90", "Ash Wood", "industrial", 0.16, "img/sk/p90_asiimov.webp", "camo", "gun"],
    ["p90-cocoa-rampage", "P90", "Cocoa Rampage", "milspec", 0.24, "img/sk/p90_asiimov.webp", "gold", "gun"],
    ["p90-death-grip", "P90", "Death Grip", "restricted", 2.9, "img/sk/p90_asiimov.webp", "teal", "gun"],
    ["p90-shapewood", "P90", "Shapewood", "classified", 6.68, "img/sk/p90_asiimov.webp", "camo", "gun"],
    ["p90-scorched", "P90", "Scorched", "consumer", 0.06, "img/sk/p90_asiimov.webp", "silver", "gun"],
    ["p90-verdant-growth", "P90", "Verdant Growth", "industrial", 0.05, "img/sk/p90_asiimov.webp", "orange", "gun"],
    ["p90-schematic", "P90", "Schematic", "milspec", 0.45, "img/sk/p90_asiimov.webp", "red", "gun"],
    ["p90-randy-rush", "P90", "Randy Rush", "restricted", 1.88, "img/sk/p90_asiimov.webp", "gold", "gun"],
    ["p90-trigon", "P90", "Trigon", "classified", 14.24, "img/sk/p90_asiimov.webp", "gold", "gun"],
    ["p90-blue-tac", "P90", "Blue Tac", "consumer", 0.03, "img/sk/p90_asiimov.webp", "blue", "gun"],
    ["p90-straight-dimes", "P90", "Straight Dimes", "industrial", 0.15, "img/sk/p90_asiimov.webp", "teal", "gun"],
    ["p90-elite-build", "P90", "Elite Build", "milspec", 0.46, "img/sk/p90_asiimov.webp", "pink", "gun"],
    ["p90-vent-rush", "P90", "Vent Rush", "restricted", 3.73, "img/sk/p90_asiimov.webp", "purple", "gun"],
    ["p90-emerald-dragon", "P90", "Emerald Dragon", "classified", 6.72, "img/sk/p90_asiimov.webp", "red", "gun"],
    ["p90-ancient-earth", "P90", "Ancient Earth", "consumer", 0.08, "img/sk/p90_asiimov.webp", "silver", "gun"],
    ["p90-mustard-gas", "P90", "Mustard Gas", "industrial", 0.13, "img/sk/p90_asiimov.webp", "blue", "gun"],
    ["p90-facility-negative", "P90", "Facility Negative", "milspec", 0.46, "img/sk/p90_asiimov.webp", "red", "gun"],
    ["p90-chopper", "P90", "Chopper", "restricted", 3.03, "img/sk/p90_asiimov.webp", "gold", "gun"],
    ["mac-10-neon-rider", "MAC-10", "Neon Rider", "covert", 9, "img/sk/mac10_neon_rider.webp", "none", "gun"],
    ["mac-10-bronzer", "MAC-10", "Bronzer", "consumer", 0.05, "img/sk/base_mac10.webp", "gold", "gun"],
    ["mac-10-acid-hex", "MAC-10", "Acid Hex", "industrial", 0.18, "img/sk/base_mac10.webp", "green", "gun"],
    ["mac-10-whitefish", "MAC-10", "Whitefish", "milspec", 0.26, "img/sk/base_mac10.webp", "white", "gun"],
    ["mac-10-gold-brick", "MAC-10", "Gold Brick", "restricted", 4.17, "img/sk/base_mac10.webp", "gold", "gun"],
    ["mac-10-hot-snakes", "MAC-10", "Hot Snakes", "classified", 8.53, "img/sk/base_mac10.webp", "purple", "gun"],
    ["mac-10-stalker", "MAC-10", "Stalker", "covert", 42.46, "img/sk/base_mac10.webp", "red", "gun"],
    ["mac-10-indigo", "MAC-10", "Indigo", "consumer", 0.05, "img/sk/base_mac10.webp", "pink", "gun"],
    ["mac-10-video-cam", "MAC-10", "Video Cam", "industrial", 0.19, "img/sk/base_mac10.webp", "green", "gun"],
    ["mac-10-pipsqueak", "MAC-10", "Pipsqueak", "milspec", 1.03, "img/sk/base_mac10.webp", "pink", "gun"],
    ["mac-10-pipe-down", "MAC-10", "Pipe Down", "restricted", 2.94, "img/sk/base_mac10.webp", "blue", "gun"],
    ["mac-10-toybox", "MAC-10", "Toybox", "classified", 13.5, "img/sk/base_mac10.webp", "red", "gun"],
    ["mac-10-surfwood", "MAC-10", "Surfwood", "consumer", 0.03, "img/sk/base_mac10.webp", "camo", "gun"],
    ["mac-10-candy-apple", "MAC-10", "Candy Apple", "industrial", 0.08, "img/sk/base_mac10.webp", "pink", "gun"],
    ["mac-10-ensnared", "MAC-10", "Ensnared", "milspec", 0.62, "img/sk/base_mac10.webp", "red", "gun"],
    ["mac-10-saiba-oni", "MAC-10", "Saibā Oni", "restricted", 6.6, "img/sk/base_mac10.webp", "pink", "gun"],
    ["mac-10-propaganda", "MAC-10", "Propaganda", "classified", 8.58, "img/sk/base_mac10.webp", "orange", "gun"],
    ["mac-10-urban-ddpat", "MAC-10", "Urban DDPAT", "consumer", 0.05, "img/sk/base_mac10.webp", "silver", "gun"],
    ["mac-10-commuter", "MAC-10", "Commuter", "industrial", 0.19, "img/sk/base_mac10.webp", "silver", "gun"],
    ["mac-10-aloha", "MAC-10", "Aloha", "milspec", 0.57, "img/sk/base_mac10.webp", "silver", "gun"],
    ["mac-10-curse", "MAC-10", "Curse", "restricted", 2.99, "img/sk/base_mac10.webp", "blue", "gun"],
    ["mac-10-disco-tech", "MAC-10", "Disco Tech", "classified", 12.69, "img/sk/base_mac10.webp", "orange", "gun"],
    ["mac-10-sienna-damask", "MAC-10", "Sienna Damask", "consumer", 0.03, "img/sk/base_mac10.webp", "teal", "gun"],
    ["mac-10-echoing-sands", "MAC-10", "Echoing Sands", "industrial", 0.21, "img/sk/base_mac10.webp", "camo", "gun"],
    ["mac-10-nuclear-garden", "MAC-10", "Nuclear Garden", "milspec", 0.63, "img/sk/base_mac10.webp", "green", "gun"],
    ["mac-10-button-masher", "MAC-10", "Button Masher", "restricted", 1.66, "img/sk/base_mac10.webp", "green", "gun"],
    ["mac-10-strats", "MAC-10", "Strats", "consumer", 0.04, "img/sk/base_mac10.webp", "orange", "gun"],
    ["mac-10-palm", "MAC-10", "Palm", "industrial", 0.27, "img/sk/base_mac10.webp", "purple", "gun"],
    ["mac-10-rangeen", "MAC-10", "Rangeen", "milspec", 1.61, "img/sk/base_mac10.webp", "teal", "gun"],
    ["mac-10-last-dive", "MAC-10", "Last Dive", "restricted", 2.87, "img/sk/base_mac10.webp", "green", "gun"],
    ["mac-10-storm-camo", "MAC-10", "Storm Camo", "consumer", 0.06, "img/sk/base_mac10.webp", "blue", "gun"],
    ["mac-10-calf-skin", "MAC-10", "Calf Skin", "industrial", 0.28, "img/sk/base_mac10.webp", "orange", "gun"],
    ["mac-10-light-box", "MAC-10", "Light Box", "milspec", 0.76, "img/sk/base_mac10.webp", "pink", "gun"],
    ["mac-10-graven", "MAC-10", "Graven", "restricted", 1.4, "img/sk/base_mac10.webp", "teal", "gun"],
    ["mac-10-tornado", "MAC-10", "Tornado", "consumer", 0.04, "img/sk/base_mac10.webp", "blue", "gun"],
    ["mac-10-silver", "MAC-10", "Silver", "industrial", 0.16, "img/sk/base_mac10.webp", "silver", "gun"],
    ["r8-revolver-fade", "R8 Revolver", "Fade", "covert", 22, "img/sk/r8_fade.webp", "none", "gun"],
    ["r8-revolver-night", "R8 Revolver", "Night", "consumer", 0.05, "img/sk/r8_fade.webp", "black", "gun"],
    ["r8-revolver-nitro", "R8 Revolver", "Nitro", "industrial", 0.3, "img/sk/r8_fade.webp", "blue", "gun"],
    ["r8-revolver-blaze", "R8 Revolver", "Blaze", "milspec", 1.19, "img/sk/r8_fade.webp", "red", "gun"],
    ["r8-revolver-crazy-8", "R8 Revolver", "Crazy 8", "restricted", 3.18, "img/sk/r8_fade.webp", "silver", "gun"],
    ["r8-revolver-amber-fade", "R8 Revolver", "Amber Fade", "classified", 10.32, "img/sk/r8_fade.webp", "orange", "gun"],
    ["r8-revolver-mauve-aside", "R8 Revolver", "Mauve Aside", "consumer", 0.08, "img/sk/r8_fade.webp", "green", "gun"],
    ["r8-revolver-leafhopper", "R8 Revolver", "Leafhopper", "industrial", 0.14, "img/sk/r8_fade.webp", "green", "gun"],
    ["r8-revolver-crimson-web", "R8 Revolver", "Crimson Web", "milspec", 0.32, "img/sk/r8_fade.webp", "red", "gun"],
    ["r8-revolver-reboot", "R8 Revolver", "Reboot", "restricted", 0.63, "img/sk/r8_fade.webp", "pink", "gun"],
    ["r8-revolver-llama-cannon", "R8 Revolver", "Llama Cannon", "classified", 11.14, "img/sk/r8_fade.webp", "purple", "gun"],
    ["r8-revolver-desert-brush", "R8 Revolver", "Desert Brush", "consumer", 0.05, "img/sk/r8_fade.webp", "camo", "gun"],
    ["r8-revolver-phoenix-marker", "R8 Revolver", "Phoenix Marker", "industrial", 0.12, "img/sk/r8_fade.webp", "orange", "gun"],
    ["r8-revolver-survivalist", "R8 Revolver", "Survivalist", "milspec", 0.88, "img/sk/r8_fade.webp", "green", "gun"],
    ["r8-revolver-banana-cannon", "R8 Revolver", "Banana Cannon", "restricted", 5.15, "img/sk/r8_fade.webp", "yellow", "gun"],
    ["r8-revolver-skull-crusher", "R8 Revolver", "Skull Crusher", "classified", 10.98, "img/sk/r8_fade.webp", "pink", "gun"],
    ["r8-revolver-cobalt-grip", "R8 Revolver", "Cobalt Grip", "consumer", 0.05, "img/sk/r8_fade.webp", "blue", "gun"],
    ["r8-revolver-dark-chamber", "R8 Revolver", "Dark Chamber", "industrial", 0.15, "img/sk/r8_fade.webp", "orange", "gun"],
    ["r8-revolver-monarch", "R8 Revolver", "Monarch", "milspec", 0.45, "img/sk/r8_fade.webp", "teal", "gun"],
    ["r8-revolver-inlay", "R8 Revolver", "Inlay", "consumer", 0.05, "img/sk/r8_fade.webp", "gold", "gun"],
    ["r8-revolver-tango", "R8 Revolver", "Tango", "milspec", 1.46, "img/sk/r8_fade.webp", "camo", "gun"],
    ["r8-revolver-canal-spray", "R8 Revolver", "Canal Spray", "consumer", 0.06, "img/sk/r8_fade.webp", "orange", "gun"],
    ["r8-revolver-junk-yard", "R8 Revolver", "Junk Yard", "milspec", 0.15, "img/sk/r8_fade.webp", "pink", "gun"],
    ["r8-revolver-bone-mask", "R8 Revolver", "Bone Mask", "consumer", 0.04, "img/sk/r8_fade.webp", "white", "gun"],
    ["r8-revolver-grip", "R8 Revolver", "Grip", "milspec", 0.52, "img/sk/r8_fade.webp", "purple", "gun"],
    ["r8-revolver-memento", "R8 Revolver", "Memento", "milspec", 0.76, "img/sk/r8_fade.webp", "orange", "gun"],
    ["r8-revolver-bone-forged", "R8 Revolver", "Bone Forged", "milspec", 0.62, "img/sk/r8_fade.webp", "white", "gun"],
    ["p2000-fire-elemental", "P2000", "Fire Elemental", "covert", 12, "img/sk/p2000_fire_elemental.webp", "none", "gun"],
    ["p2000-panther-camo", "P2000", "Panther Camo", "industrial", 0.07, "img/sk/p2000_fire_elemental.webp", "camo", "gun"],
    ["p2000-imperial", "P2000", "Imperial", "milspec", 1.24, "img/sk/p2000_fire_elemental.webp", "green", "gun"],
    ["p2000-woodsman", "P2000", "Woodsman", "restricted", 1.28, "img/sk/p2000_fire_elemental.webp", "camo", "gun"],
    ["p2000-ocean-foam", "P2000", "Ocean Foam", "classified", 4.66, "img/sk/p2000_fire_elemental.webp", "teal", "gun"],
    ["p2000-granite-marbleized", "P2000", "Granite Marbleized", "industrial", 0.1, "img/sk/p2000_fire_elemental.webp", "white", "gun"],
    ["p2000-grip-tape", "P2000", "Grip Tape", "milspec", 0.73, "img/sk/p2000_fire_elemental.webp", "purple", "gun"],
    ["p2000-acid-etched", "P2000", "Acid Etched", "restricted", 2.66, "img/sk/p2000_fire_elemental.webp", "green", "gun"],
    ["p2000-imperial-dragon", "P2000", "Imperial Dragon", "classified", 36.4, "img/sk/p2000_fire_elemental.webp", "red", "gun"],
    ["p2000-pathfinder", "P2000", "Pathfinder", "industrial", 0.09, "img/sk/p2000_fire_elemental.webp", "gold", "gun"],
    ["p2000-oceanic", "P2000", "Oceanic", "milspec", 0.5, "img/sk/p2000_fire_elemental.webp", "teal", "gun"],
    ["p2000-handgun", "P2000", "Handgun", "restricted", 1.85, "img/sk/p2000_fire_elemental.webp", "gold", "gun"],
    ["p2000-wicked-sick", "P2000", "Wicked Sick", "classified", 12.66, "img/sk/p2000_fire_elemental.webp", "green", "gun"],
    ["p2000-coach-class", "P2000", "Coach Class", "industrial", 0.07, "img/sk/p2000_fire_elemental.webp", "pink", "gun"],
    ["p2000-silver", "P2000", "Silver", "milspec", 0.34, "img/sk/p2000_fire_elemental.webp", "silver", "gun"],
    ["p2000-scorpion", "P2000", "Scorpion", "restricted", 4.06, "img/sk/p2000_fire_elemental.webp", "blue", "gun"],
    ["p2000-corticera", "P2000", "Corticera", "classified", 10.47, "img/sk/p2000_fire_elemental.webp", "blue", "gun"],
    ["p2000-grassland-leaves", "P2000", "Grassland Leaves", "industrial", 0.24, "img/sk/p2000_fire_elemental.webp", "orange", "gun"],
    ["p2000-chainmail", "P2000", "Chainmail", "milspec", 0.79, "img/sk/p2000_fire_elemental.webp", "pink", "gun"],
    ["p2000-amber-fade", "P2000", "Amber Fade", "restricted", 3.98, "img/sk/p2000_fire_elemental.webp", "orange", "gun"],
    ["p2000-grassland", "P2000", "Grassland", "industrial", 0.07, "img/sk/p2000_fire_elemental.webp", "green", "gun"],
    ["p2000-gnarled", "P2000", "Gnarled", "milspec", 0.53, "img/sk/p2000_fire_elemental.webp", "pink", "gun"],
    ["p2000-obsidian", "P2000", "Obsidian", "restricted", 2.11, "img/sk/p2000_fire_elemental.webp", "black", "gun"],
    ["p2000-coral-halftone", "P2000", "Coral Halftone", "industrial", 0.1, "img/sk/p2000_fire_elemental.webp", "teal", "gun"],
    ["p2000-dispatch", "P2000", "Dispatch", "milspec", 0.78, "img/sk/p2000_fire_elemental.webp", "teal", "gun"],
    ["p2000-space-race", "P2000", "Space Race", "restricted", 2.58, "img/sk/p2000_fire_elemental.webp", "gold", "gun"],
    ["p2000-marsh", "P2000", "Marsh", "industrial", 0.14, "img/sk/p2000_fire_elemental.webp", "orange", "gun"],
    ["p2000-urban-hazard", "P2000", "Urban Hazard", "milspec", 0.4, "img/sk/p2000_fire_elemental.webp", "silver", "gun"],
    ["p2000-red-wing", "P2000", "Red Wing", "milspec", 0.62, "img/sk/p2000_fire_elemental.webp", "red", "gun"],
    ["p2000-lifted-spirits", "P2000", "Lifted Spirits", "milspec", 0.5, "img/sk/p2000_fire_elemental.webp", "red", "gun"],
    ["p2000-turf", "P2000", "Turf", "milspec", 0.77, "img/sk/p2000_fire_elemental.webp", "green", "gun"],
    ["p2000-royal-baroque", "P2000", "Royal Baroque", "milspec", 0.61, "img/sk/p2000_fire_elemental.webp", "blue", "gun"],
    ["p2000-ivory", "P2000", "Ivory", "milspec", 0.54, "img/sk/p2000_fire_elemental.webp", "white", "gun"],
    ["p2000-sure-grip", "P2000", "Sure Grip", "milspec", 1.2, "img/sk/p2000_fire_elemental.webp", "purple", "gun"],
    ["p2000-red-fragcam", "P2000", "Red FragCam", "milspec", 0.34, "img/sk/p2000_fire_elemental.webp", "red", "gun"],
    ["p2000-pulse", "P2000", "Pulse", "milspec", 0.77, "img/sk/p2000_fire_elemental.webp", "pink", "gun"],
    ["mp5-sd-dirt-drop", "MP5-SD", "Dirt Drop", "consumer", 0.06, "img/sk/base_mp5sd.webp", "gold", "gun"],
    ["mp5-sd-neon-squeezer", "MP5-SD", "Neon Squeezer", "industrial", 0.17, "img/sk/base_mp5sd.webp", "teal", "gun"],
    ["mp5-sd-necro-jr", "MP5-SD", "Necro Jr.", "milspec", 0.6, "img/sk/base_mp5sd.webp", "purple", "gun"],
    ["mp5-sd-kitbash", "MP5-SD", "Kitbash", "restricted", 3.86, "img/sk/base_mp5sd.webp", "green", "gun"],
    ["mp5-sd-phosphor", "MP5-SD", "Phosphor", "classified", 16.25, "img/sk/base_mp5sd.webp", "pink", "gun"],
    ["mp5-sd-bamboo-garden", "MP5-SD", "Bamboo Garden", "consumer", 0.08, "img/sk/base_mp5sd.webp", "orange", "gun"],
    ["mp5-sd-nitro", "MP5-SD", "Nitro", "industrial", 0.04, "img/sk/base_mp5sd.webp", "gold", "gun"],
    ["mp5-sd-liquidation", "MP5-SD", "Liquidation", "milspec", 0.45, "img/sk/base_mp5sd.webp", "purple", "gun"],
    ["mp5-sd-gauss", "MP5-SD", "Gauss", "restricted", 6.26, "img/sk/base_mp5sd.webp", "blue", "gun"],
    ["mp5-sd-oxide-oasis", "MP5-SD", "Oxide Oasis", "classified", 6.73, "img/sk/base_mp5sd.webp", "green", "gun"],
    ["mp5-sd-lime-hex", "MP5-SD", "Lime Hex", "consumer", 0.07, "img/sk/base_mp5sd.webp", "blue", "gun"],
    ["mp5-sd-snow-splash", "MP5-SD", "Snow Splash", "industrial", 0.17, "img/sk/base_mp5sd.webp", "white", "gun"],
    ["mp5-sd-gold-leaf", "MP5-SD", "Gold Leaf", "milspec", 1.4, "img/sk/base_mp5sd.webp", "green", "gun"],
    ["mp5-sd-autumn-twilly", "MP5-SD", "Autumn Twilly", "restricted", 5.24, "img/sk/base_mp5sd.webp", "orange", "gun"],
    ["mp5-sd-savannah-halftone", "MP5-SD", "Savannah Halftone", "industrial", 0.1, "img/sk/base_mp5sd.webp", "blue", "gun"],
    ["mp5-sd-condition-zero", "MP5-SD", "Condition Zero", "milspec", 0.81, "img/sk/base_mp5sd.webp", "teal", "gun"],
    ["mp5-sd-lab-rats", "MP5-SD", "Lab Rats", "restricted", 1.1, "img/sk/base_mp5sd.webp", "orange", "gun"],
    ["mp5-sd-picnic", "MP5-SD", "Picnic", "industrial", 0.16, "img/sk/base_mp5sd.webp", "red", "gun"],
    ["mp5-sd-focus", "MP5-SD", "Focus", "milspec", 0.67, "img/sk/base_mp5sd.webp", "teal", "gun"],
    ["mp5-sd-agent", "MP5-SD", "Agent", "restricted", 1.42, "img/sk/base_mp5sd.webp", "blue", "gun"],
    ["mp5-sd-acid-wash", "MP5-SD", "Acid Wash", "milspec", 0.34, "img/sk/base_mp5sd.webp", "green", "gun"],
    ["mp5-sd-co-processor", "MP5-SD", "Co-Processor", "milspec", 0.73, "img/sk/base_mp5sd.webp", "pink", "gun"],
    ["mp5-sd-desert-strike", "MP5-SD", "Desert Strike", "milspec", 0.64, "img/sk/base_mp5sd.webp", "camo", "gun"],
    ["mp5-sd-statics", "MP5-SD", "Statics", "milspec", 0.72, "img/sk/base_mp5sd.webp", "teal", "gun"],
    ["nova-predator", "Nova", "Predator", "consumer", 0.03, "img/sk/base_nova.webp", "red", "gun"],
    ["nova-rust-coat", "Nova", "Rust Coat", "industrial", 0.15, "img/sk/base_nova.webp", "orange", "gun"],
    ["nova-blaze-orange", "Nova", "Blaze Orange", "milspec", 1.02, "img/sk/base_nova.webp", "red", "gun"],
    ["nova-toy-soldier", "Nova", "Toy Soldier", "restricted", 3.75, "img/sk/base_nova.webp", "red", "gun"],
    ["nova-bloomstick", "Nova", "Bloomstick", "classified", 16.71, "img/sk/base_nova.webp", "teal", "gun"],
    ["nova-marsh-grass", "Nova", "Marsh Grass", "consumer", 0.04, "img/sk/base_nova.webp", "blue", "gun"],
    ["nova-morning-sun", "Nova", "Morning Sun", "industrial", 0.28, "img/sk/base_nova.webp", "gold", "gun"],
    ["nova-plume", "Nova", "Plume", "milspec", 0.52, "img/sk/base_nova.webp", "purple", "gun"],
    ["nova-graphite", "Nova", "Graphite", "restricted", 3.37, "img/sk/base_nova.webp", "black", "gun"],
    ["nova-hyper-beast", "Nova", "Hyper Beast", "classified", 19.35, "img/sk/base_nova.webp", "orange", "gun"],
    ["nova-polar-mesh", "Nova", "Polar Mesh", "consumer", 0.06, "img/sk/base_nova.webp", "white", "gun"],
    ["nova-turquoise-pour", "Nova", "Turquoise Pour", "industrial", 0.09, "img/sk/base_nova.webp", "teal", "gun"],
    ["nova-ghost-camo", "Nova", "Ghost Camo", "milspec", 0.46, "img/sk/base_nova.webp", "white", "gun"],
    ["nova-clear-polymer", "Nova", "Clear Polymer", "restricted", 2.45, "img/sk/base_nova.webp", "silver", "gun"],
    ["nova-antique", "Nova", "Antique", "classified", 8.17, "img/sk/base_nova.webp", "pink", "gun"],
    ["nova-walnut", "Nova", "Walnut", "consumer", 0.03, "img/sk/base_nova.webp", "camo", "gun"],
    ["nova-green-apple", "Nova", "Green Apple", "industrial", 0.05, "img/sk/base_nova.webp", "green", "gun"],
    ["nova-modern-hunter", "Nova", "Modern Hunter", "milspec", 1.27, "img/sk/base_nova.webp", "camo", "gun"],
    ["nova-rising-sun", "Nova", "Rising Sun", "restricted", 4.06, "img/sk/base_nova.webp", "gold", "gun"],
    ["nova-sand-dune", "Nova", "Sand Dune", "consumer", 0.03, "img/sk/base_nova.webp", "camo", "gun"],
    ["nova-rain-station", "Nova", "Rain Station", "industrial", 0.07, "img/sk/base_nova.webp", "green", "gun"],
    ["nova-ranger", "Nova", "Ranger", "milspec", 0.6, "img/sk/base_nova.webp", "teal", "gun"],
    ["nova-red-quartz", "Nova", "Red Quartz", "restricted", 3.51, "img/sk/base_nova.webp", "red", "gun"],
    ["nova-forest-leaves", "Nova", "Forest Leaves", "consumer", 0.04, "img/sk/base_nova.webp", "green", "gun"],
    ["nova-caged-steel", "Nova", "Caged Steel", "industrial", 0.19, "img/sk/base_nova.webp", "silver", "gun"],
    ["nova-exo", "Nova", "Exo", "milspec", 0.48, "img/sk/base_nova.webp", "blue", "gun"],
    ["nova-rising-skull", "Nova", "Rising Skull", "restricted", 10.31, "img/sk/base_nova.webp", "green", "gun"],
    ["nova-currents", "Nova", "Currents", "consumer", 0.04, "img/sk/base_nova.webp", "pink", "gun"],
    ["nova-candy-apple", "Nova", "Candy Apple", "industrial", 0.09, "img/sk/base_nova.webp", "pink", "gun"],
    ["nova-wurst-holle", "Nova", "Wurst Hölle", "milspec", 0.39, "img/sk/base_nova.webp", "red", "gun"],
    ["nova-sobek-s-bite", "Nova", "Sobek's Bite", "restricted", 3.55, "img/sk/base_nova.webp", "pink", "gun"],
    ["nova-moon-in-libra", "Nova", "Moon in Libra", "consumer", 0.03, "img/sk/base_nova.webp", "green", "gun"],
    ["nova-quick-sand", "Nova", "Quick Sand", "milspec", 0.78, "img/sk/base_nova.webp", "camo", "gun"],
    ["nova-gila", "Nova", "Gila", "restricted", 1.02, "img/sk/base_nova.webp", "purple", "gun"],
    ["nova-army-sheen", "Nova", "Army Sheen", "consumer", 0.04, "img/sk/base_nova.webp", "green", "gun"],
    ["nova-yorkshire", "Nova", "Yorkshire", "milspec", 0.19, "img/sk/base_nova.webp", "blue", "gun"],
    ["sg-553-army-sheen", "SG 553", "Army Sheen", "consumer", 0.03, "img/sk/base_sg553.webp", "green", "gun"],
    ["sg-553-basket-halftone", "SG 553", "Basket Halftone", "industrial", 0.39, "img/sk/base_sg553.webp", "teal", "gun"],
    ["sg-553-berry-gel-coat", "SG 553", "Berry Gel Coat", "milspec", 0.4, "img/sk/base_sg553.webp", "red", "gun"],
    ["sg-553-dragon-tech", "SG 553", "Dragon Tech", "restricted", 7.72, "img/sk/base_sg553.webp", "red", "gun"],
    ["sg-553-colony-iv", "SG 553", "Colony IV", "classified", 25.74, "img/sk/base_sg553.webp", "purple", "gun"],
    ["sg-553-waves-perforated", "SG 553", "Waves Perforated", "consumer", 0.08, "img/sk/base_sg553.webp", "gold", "gun"],
    ["sg-553-traveler", "SG 553", "Traveler", "industrial", 0.15, "img/sk/base_sg553.webp", "blue", "gun"],
    ["sg-553-ol-rusty", "SG 553", "Ol' Rusty", "milspec", 0.68, "img/sk/base_sg553.webp", "orange", "gun"],
    ["sg-553-triarch", "SG 553", "Triarch", "restricted", 2.52, "img/sk/base_sg553.webp", "pink", "gun"],
    ["sg-553-integrale", "SG 553", "Integrale", "classified", 12.22, "img/sk/base_sg553.webp", "blue", "gun"],
    ["sg-553-barricade", "SG 553", "Barricade", "consumer", 0.03, "img/sk/base_sg553.webp", "silver", "gun"],
    ["sg-553-gator-mesh", "SG 553", "Gator Mesh", "industrial", 0.21, "img/sk/base_sg553.webp", "green", "gun"],
    ["sg-553-atlas", "SG 553", "Atlas", "milspec", 0.47, "img/sk/base_sg553.webp", "orange", "gun"],
    ["sg-553-darkwing", "SG 553", "Darkwing", "restricted", 2.22, "img/sk/base_sg553.webp", "black", "gun"],
    ["sg-553-cyrex", "SG 553", "Cyrex", "classified", 6.36, "img/sk/base_sg553.webp", "teal", "gun"],
    ["sg-553-night-camo", "SG 553", "Night Camo", "consumer", 0.03, "img/sk/base_sg553.webp", "black", "gun"],
    ["sg-553-candy-apple", "SG 553", "Candy Apple", "industrial", 0.07, "img/sk/base_sg553.webp", "pink", "gun"],
    ["sg-553-aloha", "SG 553", "Aloha", "milspec", 1.09, "img/sk/base_sg553.webp", "green", "gun"],
    ["sg-553-phantom", "SG 553", "Phantom", "restricted", 3.17, "img/sk/base_sg553.webp", "purple", "gun"],
    ["sg-553-hazard-pay", "SG 553", "Hazard Pay", "classified", 40.92, "img/sk/base_sg553.webp", "purple", "gun"],
    ["sg-553-tornado", "SG 553", "Tornado", "consumer", 0.06, "img/sk/base_sg553.webp", "green", "gun"],
    ["sg-553-fallout-warning", "SG 553", "Fallout Warning", "industrial", 0.24, "img/sk/base_sg553.webp", "green", "gun"],
    ["sg-553-aerial", "SG 553", "Aerial", "milspec", 0.27, "img/sk/base_sg553.webp", "orange", "gun"],
    ["sg-553-tiger-moth", "SG 553", "Tiger Moth", "restricted", 1.4, "img/sk/base_sg553.webp", "orange", "gun"],
    ["sg-553-safari-print", "SG 553", "Safari Print", "consumer", 0.07, "img/sk/base_sg553.webp", "camo", "gun"],
    ["sg-553-anodized-navy", "SG 553", "Anodized Navy", "milspec", 0.49, "img/sk/base_sg553.webp", "blue", "gun"],
    ["sg-553-bulldozer", "SG 553", "Bulldozer", "restricted", 3.85, "img/sk/base_sg553.webp", "red", "gun"],
    ["sg-553-bleached", "SG 553", "Bleached", "consumer", 0.06, "img/sk/base_sg553.webp", "orange", "gun"],
    ["sg-553-danger-close", "SG 553", "Danger Close", "milspec", 0.46, "img/sk/base_sg553.webp", "pink", "gun"],
    ["sg-553-hypnotic", "SG 553", "Hypnotic", "restricted", 2.95, "img/sk/base_sg553.webp", "silver", "gun"],
    ["sg-553-lush-ruins", "SG 553", "Lush Ruins", "consumer", 0.08, "img/sk/base_sg553.webp", "silver", "gun"],
    ["sg-553-heavy-metal", "SG 553", "Heavy Metal", "milspec", 0.34, "img/sk/base_sg553.webp", "silver", "gun"],
    ["sg-553-pulse", "SG 553", "Pulse", "restricted", 7.26, "img/sk/base_sg553.webp", "pink", "gun"],
    ["sg-553-ultraviolet", "SG 553", "Ultraviolet", "milspec", 0.74, "img/sk/base_sg553.webp", "purple", "gun"],
    ["sg-553-desert-blossom", "SG 553", "Desert Blossom", "milspec", 0.45, "img/sk/base_sg553.webp", "camo", "gun"],
    ["sg-553-damascus-steel", "SG 553", "Damascus Steel", "milspec", 0.48, "img/sk/base_sg553.webp", "silver", "gun"],
    ["xm1014-hieroglyph", "XM1014", "Hieroglyph", "consumer", 0.05, "img/sk/base_xm1014.webp", "purple", "gun"],
    ["xm1014-black-site", "XM1014", "Black Site", "industrial", 0.37, "img/sk/base_xm1014.webp", "black", "gun"],
    ["xm1014-mockingbird", "XM1014", "Mockingbird", "milspec", 0.57, "img/sk/base_xm1014.webp", "gold", "gun"],
    ["xm1014-black-tie", "XM1014", "Black Tie", "restricted", 2.59, "img/sk/base_xm1014.webp", "black", "gun"],
    ["xm1014-xoxo", "XM1014", "XOXO", "classified", 10.91, "img/sk/base_xm1014.webp", "orange", "gun"],
    ["xm1014-urban-perforated", "XM1014", "Urban Perforated", "consumer", 0.03, "img/sk/base_xm1014.webp", "silver", "gun"],
    ["xm1014-calicamo", "XM1014", "CaliCamo", "industrial", 0.22, "img/sk/base_xm1014.webp", "camo", "gun"],
    ["xm1014-slipstream", "XM1014", "Slipstream", "milspec", 0.66, "img/sk/base_xm1014.webp", "green", "gun"],
    ["xm1014-elegant-vines", "XM1014", "Elegant Vines", "restricted", 3.69, "img/sk/base_xm1014.webp", "silver", "gun"],
    ["xm1014-incinegator", "XM1014", "Incinegator", "classified", 8.01, "img/sk/base_xm1014.webp", "gold", "gun"],
    ["xm1014-canvas-cloud", "XM1014", "Canvas Cloud", "consumer", 0.04, "img/sk/base_xm1014.webp", "green", "gun"],
    ["xm1014-gum-wall-camo", "XM1014", "Gum Wall Camo", "industrial", 0.3, "img/sk/base_xm1014.webp", "camo", "gun"],
    ["xm1014-irezumi", "XM1014", "Irezumi", "milspec", 1.03, "img/sk/base_xm1014.webp", "silver", "gun"],
    ["xm1014-ziggy", "XM1014", "Ziggy", "restricted", 2.12, "img/sk/base_xm1014.webp", "teal", "gun"],
    ["xm1014-entombed", "XM1014", "Entombed", "classified", 10.16, "img/sk/base_xm1014.webp", "teal", "gun"],
    ["xm1014-grassland", "XM1014", "Grassland", "consumer", 0.04, "img/sk/base_xm1014.webp", "gold", "gun"],
    ["xm1014-banana-leaf", "XM1014", "Banana Leaf", "industrial", 0.16, "img/sk/base_xm1014.webp", "green", "gun"],
    ["xm1014-copperflage", "XM1014", "Copperflage", "milspec", 0.7, "img/sk/base_xm1014.webp", "orange", "gun"],
    ["xm1014-zombie-offensive", "XM1014", "Zombie Offensive", "restricted", 1.94, "img/sk/base_xm1014.webp", "teal", "gun"],
    ["xm1014-tranquility", "XM1014", "Tranquility", "classified", 11.41, "img/sk/base_xm1014.webp", "green", "gun"],
    ["xm1014-jungle", "XM1014", "Jungle", "consumer", 0.04, "img/sk/base_xm1014.webp", "green", "gun"],
    ["xm1014-blue-steel", "XM1014", "Blue Steel", "industrial", 0.11, "img/sk/base_xm1014.webp", "blue", "gun"],
    ["xm1014-blaze-orange", "XM1014", "Blaze Orange", "milspec", 0.51, "img/sk/base_xm1014.webp", "red", "gun"],
    ["xm1014-seasons", "XM1014", "Seasons", "restricted", 6.99, "img/sk/base_xm1014.webp", "teal", "gun"],
    ["xm1014-blue-tire", "XM1014", "Blue Tire", "consumer", 0.04, "img/sk/base_xm1014.webp", "blue", "gun"],
    ["xm1014-xooom", "XM1014", "XoooM", "industrial", 0.17, "img/sk/base_xm1014.webp", "teal", "gun"],
    ["xm1014-varicamo-blue", "XM1014", "VariCamo Blue", "milspec", 0.42, "img/sk/base_xm1014.webp", "blue", "gun"],
    ["xm1014-heaven-guard", "XM1014", "Heaven Guard", "restricted", 2.47, "img/sk/base_xm1014.webp", "gold", "gun"],
    ["xm1014-charter", "XM1014", "Charter", "consumer", 0.05, "img/sk/base_xm1014.webp", "blue", "gun"],
    ["xm1014-fallout-warning", "XM1014", "Fallout Warning", "industrial", 0.14, "img/sk/base_xm1014.webp", "teal", "gun"],
    ["xm1014-halftone-shift", "XM1014", "Halftone Shift", "milspec", 0.76, "img/sk/base_xm1014.webp", "green", "gun"],
    ["xm1014-teclu-burner", "XM1014", "Teclu Burner", "restricted", 3.22, "img/sk/base_xm1014.webp", "orange", "gun"],
    ["xm1014-blue-spruce", "XM1014", "Blue Spruce", "consumer", 0.12, "img/sk/base_xm1014.webp", "blue", "gun"],
    ["xm1014-quicksilver", "XM1014", "Quicksilver", "milspec", 0.67, "img/sk/base_xm1014.webp", "silver", "gun"],
    ["xm1014-ancient-lore", "XM1014", "Ancient Lore", "restricted", 3.01, "img/sk/base_xm1014.webp", "gold", "gun"],
    ["xm1014-watchdog", "XM1014", "Watchdog", "milspec", 0.59, "img/sk/base_xm1014.webp", "gold", "gun"],
    ["broken-fang-gloves-jade", "★ Broken Fang Gloves", "Jade", "gold", 93.47, "img/sk/base_gloves_ct.webp", "teal", "gloves"],
    ["specialist-gloves-forest-ddpat", "★ Specialist Gloves", "Forest DDPAT", "gold", 82.02, "img/sk/base_gloves_t.webp", "green", "gloves"],
    ["driver-gloves-wave-chaser", "★ Driver Gloves", "Wave Chaser", "gold", 237.74, "img/sk/base_gloves_ct.webp", "pink", "gloves"],
    ["specialist-gloves-emerald-web", "★ Specialist Gloves", "Emerald Web", "gold", 121.74, "img/sk/base_gloves_ct.webp", "green", "gloves"],
    ["sport-gloves-blaze", "★ Sport Gloves", "Blaze", "gold", 91.18, "img/sk/base_gloves_ct.webp", "red", "gloves"],
    ["driver-gloves-crimson-weave", "★ Driver Gloves", "Crimson Weave", "gold", 106.54, "img/sk/base_gloves_t.webp", "red", "gloves"],
    ["specialist-gloves-tiger-strike", "★ Specialist Gloves", "Tiger Strike", "gold", 55.37, "img/sk/base_gloves_ct.webp", "orange", "gloves"],
    ["sport-gloves-ultra-violent", "★ Sport Gloves", "Ultra Violent", "gold", 106.61, "img/sk/base_gloves_t.webp", "green", "gloves"],
    ["driver-gloves-lunar-weave", "★ Driver Gloves", "Lunar Weave", "gold", 105.86, "img/sk/base_gloves_ct.webp", "orange", "gloves"],
    ["moto-gloves-blood-pressure", "★ Moto Gloves", "Blood Pressure", "gold", 81.64, "img/sk/base_gloves_t.webp", "red", "gloves"],
    ["hand-wraps-spruce-ddpat", "★ Hand Wraps", "Spruce DDPAT", "gold", 128.1, "img/sk/base_gloves_t.webp", "camo", "gloves"],
    ["driver-gloves-rezan-the-red", "★ Driver Gloves", "Rezan the Red", "gold", 57.45, "img/sk/base_gloves_t.webp", "red", "gloves"],
    ["sport-gloves-red-racer", "★ Sport Gloves", "Red Racer", "gold", 110.18, "img/sk/base_gloves_ct.webp", "red", "gloves"],
    ["broken-fang-gloves-yellow-banded", "★ Broken Fang Gloves", "Yellow-banded", "gold", 51.78, "img/sk/base_gloves_t.webp", "yellow", "gloves"],
    ["specialist-gloves-chocolate-chesterfield", "★ Specialist Gloves", "Chocolate Chesterfield", "gold", 187.65, "img/sk/base_gloves_t.webp", "silver", "gloves"],
    ["hand-wraps-duct-tape", "★ Hand Wraps", "Duct Tape", "gold", 88.44, "img/sk/base_gloves_ct.webp", "silver", "gloves"],
    ["specialist-gloves-marble-fade", "★ Specialist Gloves", "Marble Fade", "gold", 400.03, "img/sk/base_gloves_ct.webp", "white", "gloves"],
    ["moto-gloves-3rd-commando-company", "★ Moto Gloves", "3rd Commando Company", "gold", 348.49, "img/sk/base_gloves_t.webp", "pink", "gloves"],
    ["bloodhound-gloves-snakebite", "★ Bloodhound Gloves", "Snakebite", "gold", 121.19, "img/sk/base_gloves_ct.webp", "orange", "gloves"],
    ["specialist-gloves-lt-commander", "★ Specialist Gloves", "Lt. Commander", "gold", 111.88, "img/sk/base_gloves_ct.webp", "orange", "gloves"],
    ["moto-gloves-turtle", "★ Moto Gloves", "Turtle", "gold", 156.09, "img/sk/base_gloves_t.webp", "gold", "gloves"],
    ["hand-wraps-caution", "★ Hand Wraps", "CAUTION!", "gold", 95.2, "img/sk/base_gloves_ct.webp", "red", "gloves"],
    ["moto-gloves-smoke-out", "★ Moto Gloves", "Smoke Out", "gold", 114.29, "img/sk/base_gloves_ct.webp", "purple", "gloves"],
    ["driver-gloves-hand-sweaters", "★ Driver Gloves", "Hand Sweaters", "gold", 162.7, "img/sk/base_gloves_ct.webp", "gold", "gloves"],
    ["bloodhound-gloves-bronzed", "★ Bloodhound Gloves", "Bronzed", "gold", 74.94, "img/sk/base_gloves_ct.webp", "gold", "gloves"],
    ["sport-gloves-hedge-maze", "★ Sport Gloves", "Hedge Maze", "gold", 198.27, "img/sk/base_gloves_ct.webp", "silver", "gloves"],
    ["sport-gloves-scarlet-shamagh", "★ Sport Gloves", "Scarlet Shamagh", "gold", 175.14, "img/sk/base_gloves_t.webp", "red", "gloves"],
    ["specialist-gloves-fade", "★ Specialist Gloves", "Fade", "gold", 238.07, "img/sk/base_gloves_t.webp", "silver", "gloves"],
    ["sport-gloves-violet-beadwork", "★ Sport Gloves", "Violet Beadwork", "gold", 240.66, "img/sk/base_gloves_t.webp", "purple", "gloves"],
    ["sport-gloves-omega", "★ Sport Gloves", "Omega", "gold", 177.67, "img/sk/base_gloves_ct.webp", "blue", "gloves"],
];
const KNIFE_DATA = [
    ["karambit-gamma-doppler", "★ Karambit", "Gamma Doppler", 506.97, "karambit", "#4c1d95", "#c4b5fd", "f"],
    ["karambit-slaughter", "★ Karambit", "Slaughter", 510.63, "karambit", "#991b1b", "#f87171", "s"],
    ["karambit-ultraviolet", "★ Karambit", "Ultraviolet", 982.81, "karambit", "#4c1d95", "#c4b5fd", "f"],
    ["karambit-crimson-web", "★ Karambit", "Crimson Web", 1351.05, "karambit", "#991b1b", "#f87171", "f"],
    ["karambit-forest-ddpat", "★ Karambit", "Forest DDPAT", 905.66, "karambit", "#14532d", "#86efac", "c"],
    ["karambit-urban-masked", "★ Karambit", "Urban Masked", 448.81, "karambit", "#4b5563", "#e5e7eb", "c"],
    ["karambit-marble-fade", "★ Karambit", "Marble Fade", 733.15, "karambit", "#9ca3af", "#f9fafb", "f"],
    ["karambit-doppler", "★ Karambit", "Doppler", 610.98, "karambit", "#92400e", "#fcd34d", "f"],
    ["karambit-fade", "★ Karambit", "Fade", 1109.57, "karambit", "#4b5563", "#e5e7eb", "f"],
    ["karambit-boreal-forest", "★ Karambit", "Boreal Forest", 456.71, "karambit", "#14532d", "#86efac", "c"],
    ["karambit-bright-water", "★ Karambit", "Bright Water", 394.11, "karambit", "#1e3a8a", "#93c5fd", "c"],
    ["karambit-tiger-tooth", "★ Karambit", "Tiger Tooth", 1383.57, "karambit", "#9a3412", "#fdba74", "s"],
    ["butterfly-knife-lore", "★ Butterfly Knife", "Lore", 1861.53, "butterfly", "#92400e", "#fcd34d", "f"],
    ["butterfly-knife-crimson-web", "★ Butterfly Knife", "Crimson Web", 579.45, "butterfly", "#991b1b", "#f87171", "f"],
    ["butterfly-knife-stained", "★ Butterfly Knife", "Stained", 580.57, "butterfly", "#92400e", "#fcd34d", "c"],
    ["butterfly-knife-gamma-doppler", "★ Butterfly Knife", "Gamma Doppler", 1213.62, "butterfly", "#4c1d95", "#c4b5fd", "f"],
    ["butterfly-knife-fade", "★ Butterfly Knife", "Fade", 1306.62, "butterfly", "#4b5563", "#e5e7eb", "f"],
    ["butterfly-knife-freehand", "★ Butterfly Knife", "Freehand", 597.88, "butterfly", "#9a3412", "#fdba74", "f"],
    ["butterfly-knife-blue-steel", "★ Butterfly Knife", "Blue Steel", 408.81, "butterfly", "#1e3a8a", "#93c5fd", "f"],
    ["butterfly-knife-safari-mesh", "★ Butterfly Knife", "Safari Mesh", 322.56, "butterfly", "#3f3f2a", "#a8a37a", "c"],
    ["butterfly-knife-boreal-forest", "★ Butterfly Knife", "Boreal Forest", 290.51, "butterfly", "#14532d", "#86efac", "c"],
    ["butterfly-knife-slaughter", "★ Butterfly Knife", "Slaughter", 1924.73, "butterfly", "#991b1b", "#f87171", "s"],
    ["butterfly-knife-rust-coat", "★ Butterfly Knife", "Rust Coat", 682.03, "butterfly", "#9a3412", "#fdba74", "f"],
    ["butterfly-knife-damascus-steel", "★ Butterfly Knife", "Damascus Steel", 346.67, "butterfly", "#4b5563", "#e5e7eb", "f"],
    ["m9-bayonet-tiger-tooth", "★ M9 Bayonet", "Tiger Tooth", 1243.88, "m9", "#9a3412", "#fdba74", "s"],
    ["m9-bayonet-damascus-steel", "★ M9 Bayonet", "Damascus Steel", 586.82, "m9", "#4b5563", "#e5e7eb", "f"],
    ["m9-bayonet-gamma-doppler", "★ M9 Bayonet", "Gamma Doppler", 969.54, "m9", "#4c1d95", "#c4b5fd", "f"],
    ["m9-bayonet-case-hardened", "★ M9 Bayonet", "Case Hardened", 2170.36, "m9", "#4b5563", "#e5e7eb", "f"],
    ["m9-bayonet-slaughter", "★ M9 Bayonet", "Slaughter", 1833.65, "m9", "#991b1b", "#f87171", "s"],
    ["m9-bayonet-safari-mesh", "★ M9 Bayonet", "Safari Mesh", 388.55, "m9", "#3f3f2a", "#a8a37a", "c"],
    ["m9-bayonet-forest-ddpat", "★ M9 Bayonet", "Forest DDPAT", 944.33, "m9", "#14532d", "#86efac", "c"],
    ["m9-bayonet-black-laminate", "★ M9 Bayonet", "Black Laminate", 802.67, "m9", "#0b0f19", "#6b7280", "f"],
    ["m9-bayonet", "★ M9 Bayonet", "Vanilla", 285.25, "m9", "#4c1d95", "#c4b5fd", "f"],
    ["m9-bayonet-fade", "★ M9 Bayonet", "Fade", 2013.64, "m9", "#4b5563", "#e5e7eb", "f"],
    ["m9-bayonet-boreal-forest", "★ M9 Bayonet", "Boreal Forest", 325.96, "m9", "#14532d", "#86efac", "c"],
    ["m9-bayonet-bright-water", "★ M9 Bayonet", "Bright Water", 438.45, "m9", "#1e3a8a", "#93c5fd", "c"],
    ["bayonet-lore", "★ Bayonet", "Lore", 264.05, "bayonet", "#92400e", "#fcd34d", "f"],
    ["bayonet-damascus-steel", "★ Bayonet", "Damascus Steel", 198.32, "bayonet", "#4b5563", "#e5e7eb", "f"],
    ["bayonet-crimson-web", "★ Bayonet", "Crimson Web", 615.23, "bayonet", "#991b1b", "#f87171", "f"],
    ["bayonet-night", "★ Bayonet", "Night", 344.44, "bayonet", "#0b0f19", "#6b7280", "c"],
    ["bayonet-stained", "★ Bayonet", "Stained", 331.04, "bayonet", "#9a3412", "#fdba74", "c"],
    ["bayonet-rust-coat", "★ Bayonet", "Rust Coat", 161.49, "bayonet", "#9a3412", "#fdba74", "f"],
    ["bayonet-marble-fade", "★ Bayonet", "Marble Fade", 415.52, "bayonet", "#9ca3af", "#f9fafb", "f"],
    ["bayonet-boreal-forest", "★ Bayonet", "Boreal Forest", 191.38, "bayonet", "#14532d", "#86efac", "c"],
    ["bayonet-slaughter", "★ Bayonet", "Slaughter", 323.44, "bayonet", "#991b1b", "#f87171", "s"],
    ["bayonet-scorched", "★ Bayonet", "Scorched", 128.42, "bayonet", "#4b5563", "#e5e7eb", "c"],
    ["bayonet-autotronic", "★ Bayonet", "Autotronic", 403.14, "bayonet", "#9d174d", "#f9a8d4", "f"],
    ["bayonet-gamma-doppler", "★ Bayonet", "Gamma Doppler", 708.84, "bayonet", "#4c1d95", "#c4b5fd", "f"],
    ["talon-knife-fade", "★ Talon Knife", "Fade", 817.96, "talon", "#4b5563", "#e5e7eb", "f"],
    ["talon-knife-scorched", "★ Talon Knife", "Scorched", 228.6, "talon", "#4b5563", "#e5e7eb", "c"],
    ["talon-knife-night-stripe", "★ Talon Knife", "Night Stripe", 232.28, "talon", "#0b0f19", "#6b7280", "s"],
    ["talon-knife-ultraviolet", "★ Talon Knife", "Ultraviolet", 161.07, "talon", "#4c1d95", "#c4b5fd", "f"],
    ["talon-knife-safari-mesh", "★ Talon Knife", "Safari Mesh", 345.33, "talon", "#3f3f2a", "#a8a37a", "c"],
    ["talon-knife-stained", "★ Talon Knife", "Stained", 251.75, "talon", "#14532d", "#86efac", "c"],
    ["talon-knife-damascus-steel", "★ Talon Knife", "Damascus Steel", 158.68, "talon", "#4b5563", "#e5e7eb", "f"],
    ["talon-knife-urban-masked", "★ Talon Knife", "Urban Masked", 655.21, "talon", "#4b5563", "#e5e7eb", "c"],
    ["talon-knife-doppler", "★ Talon Knife", "Doppler", 665.09, "talon", "#1e3a8a", "#93c5fd", "f"],
    ["talon-knife-boreal-forest", "★ Talon Knife", "Boreal Forest", 653.59, "talon", "#14532d", "#86efac", "c"],
    ["talon-knife", "★ Talon Knife", "Vanilla", 331.92, "talon", "#92400e", "#fcd34d", "f"],
    ["talon-knife-crimson-web", "★ Talon Knife", "Crimson Web", 861.95, "talon", "#991b1b", "#f87171", "f"],
    ["flip-knife-safari-mesh", "★ Flip Knife", "Safari Mesh", 563.2, "bayonet", "#3f3f2a", "#a8a37a", "c"],
    ["flip-knife-gamma-doppler", "★ Flip Knife", "Gamma Doppler", 381.68, "bayonet", "#4c1d95", "#c4b5fd", "f"],
    ["flip-knife-ultraviolet", "★ Flip Knife", "Ultraviolet", 180.45, "bayonet", "#4c1d95", "#c4b5fd", "f"],
    ["flip-knife", "★ Flip Knife", "Vanilla", 175.83, "bayonet", "#1e3a8a", "#93c5fd", "f"],
    ["flip-knife-stained", "★ Flip Knife", "Stained", 224.81, "bayonet", "#9d174d", "#f9a8d4", "c"],
    ["flip-knife-night", "★ Flip Knife", "Night", 142.64, "bayonet", "#0b0f19", "#6b7280", "c"],
    ["flip-knife-damascus-steel", "★ Flip Knife", "Damascus Steel", 151.34, "bayonet", "#4b5563", "#e5e7eb", "f"],
    ["flip-knife-doppler", "★ Flip Knife", "Doppler", 460.09, "bayonet", "#14532d", "#86efac", "f"],
    ["flip-knife-fade", "★ Flip Knife", "Fade", 426.28, "bayonet", "#4b5563", "#e5e7eb", "f"],
    ["flip-knife-crimson-web", "★ Flip Knife", "Crimson Web", 196.8, "bayonet", "#991b1b", "#f87171", "f"],
    ["flip-knife-freehand", "★ Flip Knife", "Freehand", 179.11, "bayonet", "#9a3412", "#fdba74", "f"],
    ["flip-knife-scorched", "★ Flip Knife", "Scorched", 116.39, "bayonet", "#4b5563", "#e5e7eb", "c"],
    ["huntsman-knife", "★ Huntsman Knife", "Vanilla", 192.11, "talon", "#4c1d95", "#c4b5fd", "f"],
    ["huntsman-knife-safari-mesh", "★ Huntsman Knife", "Safari Mesh", 125.99, "talon", "#3f3f2a", "#a8a37a", "c"],
    ["huntsman-knife-ultraviolet", "★ Huntsman Knife", "Ultraviolet", 335.74, "talon", "#4c1d95", "#c4b5fd", "f"],
    ["huntsman-knife-freehand", "★ Huntsman Knife", "Freehand", 148.75, "talon", "#115e59", "#5eead4", "f"],
    ["huntsman-knife-rust-coat", "★ Huntsman Knife", "Rust Coat", 317.88, "talon", "#9a3412", "#fdba74", "f"],
    ["huntsman-knife-crimson-web", "★ Huntsman Knife", "Crimson Web", 139.56, "talon", "#991b1b", "#f87171", "f"],
    ["huntsman-knife-black-laminate", "★ Huntsman Knife", "Black Laminate", 136.5, "talon", "#0b0f19", "#6b7280", "f"],
    ["huntsman-knife-doppler", "★ Huntsman Knife", "Doppler", 472.53, "talon", "#4b5563", "#e5e7eb", "f"],
    ["huntsman-knife-tiger-tooth", "★ Huntsman Knife", "Tiger Tooth", 261.99, "talon", "#9a3412", "#fdba74", "s"],
    ["huntsman-knife-boreal-forest", "★ Huntsman Knife", "Boreal Forest", 139.41, "talon", "#14532d", "#86efac", "c"],
    ["huntsman-knife-blue-steel", "★ Huntsman Knife", "Blue Steel", 74.51, "talon", "#1e3a8a", "#93c5fd", "f"],
    ["huntsman-knife-urban-masked", "★ Huntsman Knife", "Urban Masked", 131.53, "talon", "#4b5563", "#e5e7eb", "c"],
    ["falchion-knife-boreal-forest", "★ Falchion Knife", "Boreal Forest", 149.2, "talon", "#14532d", "#86efac", "c"],
    ["falchion-knife-damascus-steel", "★ Falchion Knife", "Damascus Steel", 122.15, "talon", "#4b5563", "#e5e7eb", "f"],
    ["falchion-knife-lore", "★ Falchion Knife", "Lore", 243.16, "talon", "#92400e", "#fcd34d", "f"],
    ["falchion-knife-crimson-web", "★ Falchion Knife", "Crimson Web", 130.8, "talon", "#991b1b", "#f87171", "f"],
    ["falchion-knife-freehand", "★ Falchion Knife", "Freehand", 292.5, "talon", "#4b5563", "#e5e7eb", "f"],
    ["falchion-knife-bright-water", "★ Falchion Knife", "Bright Water", 67.15, "talon", "#1e3a8a", "#93c5fd", "c"],
    ["falchion-knife-stained", "★ Falchion Knife", "Stained", 167.7, "talon", "#14532d", "#86efac", "c"],
    ["falchion-knife-tiger-tooth", "★ Falchion Knife", "Tiger Tooth", 370.2, "talon", "#9a3412", "#fdba74", "s"],
    ["falchion-knife-marble-fade", "★ Falchion Knife", "Marble Fade", 151.81, "talon", "#9ca3af", "#f9fafb", "f"],
    ["falchion-knife-urban-masked", "★ Falchion Knife", "Urban Masked", 138.99, "talon", "#4b5563", "#e5e7eb", "c"],
    ["falchion-knife-night", "★ Falchion Knife", "Night", 148.58, "talon", "#0b0f19", "#6b7280", "c"],
    ["falchion-knife-rust-coat", "★ Falchion Knife", "Rust Coat", 126.34, "talon", "#9a3412", "#fdba74", "f"],
    ["bowie-knife-rust-coat", "★ Bowie Knife", "Rust Coat", 88.34, "bayonet", "#9a3412", "#fdba74", "f"],
    ["bowie-knife-urban-masked", "★ Bowie Knife", "Urban Masked", 122.24, "bayonet", "#4b5563", "#e5e7eb", "c"],
    ["bowie-knife-black-laminate", "★ Bowie Knife", "Black Laminate", 258.79, "bayonet", "#0b0f19", "#6b7280", "f"],
    ["bowie-knife-case-hardened", "★ Bowie Knife", "Case Hardened", 350.21, "bayonet", "#4c1d95", "#c4b5fd", "f"],
    ["bowie-knife-boreal-forest", "★ Bowie Knife", "Boreal Forest", 264.0, "bayonet", "#14532d", "#86efac", "c"],
    ["bowie-knife-scorched", "★ Bowie Knife", "Scorched", 233.62, "bayonet", "#4b5563", "#e5e7eb", "c"],
    ["bowie-knife-autotronic", "★ Bowie Knife", "Autotronic", 131.08, "bayonet", "#92400e", "#fcd34d", "f"],
    ["bowie-knife-slaughter", "★ Bowie Knife", "Slaughter", 390.66, "bayonet", "#991b1b", "#f87171", "s"],
    ["bowie-knife-crimson-web", "★ Bowie Knife", "Crimson Web", 385.11, "bayonet", "#991b1b", "#f87171", "f"],
    ["bowie-knife-forest-ddpat", "★ Bowie Knife", "Forest DDPAT", 100.72, "bayonet", "#14532d", "#86efac", "c"],
    ["bowie-knife-stained", "★ Bowie Knife", "Stained", 137.36, "bayonet", "#115e59", "#5eead4", "c"],
    ["bowie-knife-tiger-tooth", "★ Bowie Knife", "Tiger Tooth", 316.17, "bayonet", "#9a3412", "#fdba74", "s"],
    ["stiletto-knife-blue-steel", "★ Stiletto Knife", "Blue Steel", 157.62, "bayonet", "#1e3a8a", "#93c5fd", "f"],
    ["stiletto-knife-forest-ddpat", "★ Stiletto Knife", "Forest DDPAT", 661.92, "bayonet", "#14532d", "#86efac", "c"],
    ["stiletto-knife-marble-fade", "★ Stiletto Knife", "Marble Fade", 807.39, "bayonet", "#9ca3af", "#f9fafb", "f"],
    ["stiletto-knife-tiger-tooth", "★ Stiletto Knife", "Tiger Tooth", 745.27, "bayonet", "#9a3412", "#fdba74", "s"],
    ["stiletto-knife-damascus-steel", "★ Stiletto Knife", "Damascus Steel", 45.93, "bayonet", "#4b5563", "#e5e7eb", "f"],
    ["stiletto-knife-doppler", "★ Stiletto Knife", "Doppler", 354.25, "bayonet", "#991b1b", "#f87171", "f"],
    ["stiletto-knife-crimson-web", "★ Stiletto Knife", "Crimson Web", 415.98, "bayonet", "#991b1b", "#f87171", "f"],
    ["stiletto-knife-urban-masked", "★ Stiletto Knife", "Urban Masked", 223.67, "bayonet", "#4b5563", "#e5e7eb", "c"],
    ["stiletto-knife-stained", "★ Stiletto Knife", "Stained", 261.92, "bayonet", "#991b1b", "#f87171", "c"],
    ["stiletto-knife-rust-coat", "★ Stiletto Knife", "Rust Coat", 87.1, "bayonet", "#9a3412", "#fdba74", "f"],
    ["stiletto-knife", "★ Stiletto Knife", "Vanilla", 371.4, "bayonet", "#115e59", "#5eead4", "f"],
    ["stiletto-knife-boreal-forest", "★ Stiletto Knife", "Boreal Forest", 456.94, "bayonet", "#14532d", "#86efac", "c"],
];
const OLD_PRICES = {"ak_0": 62.0, "ak_2": 48.0, "ak_1": 17.0, "ak_3": 5.8, "ak_4": 1.3, "awp_0": 145.0, "awp_2": 95.0, "awp_1": 22.0, "awp_3": 7.5, "awp_4": 1.6, "m41_3": 54.0, "m41_0": 19.0, "m41_2": 5.1, "m41_1": 4.4, "m41_4": 0.32, "m4_1": 71.0, "m4_0": 14.0, "m4_2": 6.2, "m4_3": 1.1, "m4_4": 0.4, "gal_0": 8.9, "gal_3": 4.1, "gal_1": 3.4, "gal_2": 0.95, "gal_4": 0.12, "usp_4": 11.0, "usp_1": 3.2, "usp_0": 0.88, "usp_3": 0.33, "usp_2": 0.07, "ssg_4": 7.2, "ssg_0": 3.9, "ssg_3": 1.05, "ssg_1": 0.29, "ssg_2": 0.06, "glk_0": 9.6, "glk_1": 3.0, "glk_2": 0.8, "glk_3": 0.26, "glk_4": 0.05, "kn1": 180.0, "gl2": 190.0, "gl1": 260.0, "kn2": 320.0, "kn4": 410.0, "kn3": 540.0, "kn5": 760.0};
